/// Auto-generated by compile.js
// @ts-nocheck
import type { SolcOutput } from '@tevm/solc'

const solcOutput: SolcOutput = {
  "contracts": {
    "SimpleYul.yul": {
      "SimpleYul": {
        "evm": {
          "assembly": "    /* \"SimpleYul.yul\":89:108   */\n  dataSize(sub_0)\n    /* \"SimpleYul.yul\":66:87   */\n  dataOffset(sub_0)\n    /* \"SimpleYul.yul\":63:64   */\n  0x00\n    /* \"SimpleYul.yul\":54:109   */\n  codecopy\n    /* \"SimpleYul.yul\":132:151   */\n  dataSize(sub_0)\n    /* \"SimpleYul.yul\":129:130   */\n  0x00\n    /* \"SimpleYul.yul\":122:152   */\n  return\nstop\n\nsub_0: assembly {\n        /* \"SimpleYul.yul\":275:276   */\n      0x00\n        /* \"SimpleYul.yul\":262:277   */\n      calldataload\n        /* \"SimpleYul.yul\":257:260   */\n      0xe0\n        /* \"SimpleYul.yul\":253:278   */\n      shr\n        /* \"SimpleYul.yul\":327:454   */\n      dup1\n        /* \"SimpleYul.yul\":332:342   */\n      0x55241077\n        /* \"SimpleYul.yul\":327:454   */\n      eq\n      tag_1\n      jumpi\n        /* \"SimpleYul.yul\":476:486   */\n      0x20965255\n        /* \"SimpleYul.yul\":471:631   */\n      eq\n      tag_3\n      jumpi\n        /* \"SimpleYul.yul\":668:669   */\n      0x00\n        /* \"SimpleYul.yul\":658:670   */\n      dup1\n      revert\n        /* \"SimpleYul.yul\":487:631   */\n    tag_3:\n        /* \"SimpleYul.yul\":534:535   */\n      0x00\n        /* \"SimpleYul.yul\":528:536   */\n      sload\n        /* \"SimpleYul.yul\":564:565   */\n      0x00\n        /* \"SimpleYul.yul\":557:579   */\n      mstore\n        /* \"SimpleYul.yul\":610:612   */\n      0x20\n        /* \"SimpleYul.yul\":607:608   */\n      0x00\n        /* \"SimpleYul.yul\":600:613   */\n      return\n        /* \"SimpleYul.yul\":343:454   */\n    tag_1:\n        /* \"SimpleYul.yul\":394:395   */\n      0x04\n        /* \"SimpleYul.yul\":381:396   */\n      calldataload\n        /* \"SimpleYul.yul\":424:425   */\n      0x00\n        /* \"SimpleYul.yul\":417:436   */\n      sstore\n        /* \"SimpleYul.yul\":295:672   */\n      stop\n}\n",
          "bytecode": {
            "functionDebugData": {},
            "linkReferences": {},
            "object": "602b600b5f39602b5ff3fe5f3560e01c80635524107714602457632096525514601b575f80fd5b5f545f5260205ff35b6004355f5500",
            "opcodes": "PUSH1 0x2B PUSH1 0xB PUSH0 CODECOPY PUSH1 0x2B PUSH0 RETURN INVALID PUSH0 CALLDATALOAD PUSH1 0xE0 SHR DUP1 PUSH4 0x55241077 EQ PUSH1 0x24 JUMPI PUSH4 0x20965255 EQ PUSH1 0x1B JUMPI PUSH0 DUP1 REVERT JUMPDEST PUSH0 SLOAD PUSH0 MSTORE PUSH1 0x20 PUSH0 RETURN JUMPDEST PUSH1 0x4 CALLDATALOAD PUSH0 SSTORE STOP ",
            "sourceMap": "89:19:0:-:0;66:21;63:1;54:55;132:19;129:1;122:30"
          },
          "deployedBytecode": {
            "functionDebugData": {},
            "immutableReferences": {},
            "linkReferences": {},
            "object": "5f3560e01c80635524107714602457632096525514601b575f80fd5b5f545f5260205ff35b6004355f5500",
            "opcodes": "PUSH0 CALLDATALOAD PUSH1 0xE0 SHR DUP1 PUSH4 0x55241077 EQ PUSH1 0x24 JUMPI PUSH4 0x20965255 EQ PUSH1 0x1B JUMPI PUSH0 DUP1 REVERT JUMPDEST PUSH0 SLOAD PUSH0 MSTORE PUSH1 0x20 PUSH0 RETURN JUMPDEST PUSH1 0x4 CALLDATALOAD PUSH0 SSTORE STOP ",
            "sourceMap": "275:1:0:-:0;262:15;257:3;253:25;327:127;332:10;327:127;;;476:10;471:160;;;668:1;658:12;;487:144;534:1;528:8;564:1;557:22;610:2;607:1;600:13;343:111;394:1;381:15;424:1;417:19;295:377"
          }
        },
        "ir": "object \"SimpleYul\" {\n    code {\n        datacopy(0, dataoffset(\"Runtime\"), datasize(\"Runtime\"))\n        return(0, datasize(\"Runtime\"))\n    }\n    object \"Runtime\" {\n        code {\n            let selector := shr(224, calldataload(0))\n            switch selector\n            case 0x55241077 {\n                let newValue := calldataload(4)\n                sstore(0, newValue)\n            }\n            case 0x20965255 {\n                let storedValue := sload(0)\n                mstore(0, storedValue)\n                return(0, 32)\n            }\n            default { revert(0, 0) }\n        }\n    }\n}\n",
        "irOptimized": "object \"SimpleYul\" {\n    code {\n        {\n            datacopy(0, dataoffset(\"Runtime\"), datasize(\"Runtime\"))\n            return(0, datasize(\"Runtime\"))\n        }\n    }\n    object \"Runtime\" {\n        code {\n            {\n                let selector := shr(224, calldataload(0))\n                switch selector\n                case 0x55241077 {\n                    let newValue := calldataload(4)\n                    sstore(0, newValue)\n                }\n                case 0x20965255 {\n                    let storedValue := sload(0)\n                    mstore(0, storedValue)\n                    return(0, 32)\n                }\n                default { revert(0, 0) }\n            }\n        }\n    }\n}\n"
      }
    }
  },
  "errors": [],
  "sources": {
    "SimpleYul.yul": {
      "ast": {
        "code": {
          "block": {
            "nativeSrc": "114:132:0",
            "nodeType": "YulBlock",
            "src": "114:132:0",
            "statements": [
              {
                "expression": {
                  "arguments": [
                    {
                      "kind": "number",
                      "nativeSrc": "164:1:0",
                      "nodeType": "YulLiteral",
                      "src": "164:1:0",
                      "type": "",
                      "value": "0"
                    },
                    {
                      "arguments": [
                        {
                          "hexValue": "52756e74696d65",
                          "kind": "string",
                          "nativeSrc": "178:9:0",
                          "nodeType": "YulLiteral",
                          "src": "178:9:0",
                          "type": "",
                          "value": "Runtime"
                        }
                      ],
                      "functionName": {
                        "name": "dataoffset",
                        "nativeSrc": "167:10:0",
                        "nodeType": "YulIdentifier",
                        "src": "167:10:0"
                      },
                      "nativeSrc": "167:21:0",
                      "nodeType": "YulFunctionCall",
                      "src": "167:21:0"
                    },
                    {
                      "arguments": [
                        {
                          "hexValue": "52756e74696d65",
                          "kind": "string",
                          "nativeSrc": "199:9:0",
                          "nodeType": "YulLiteral",
                          "src": "199:9:0",
                          "type": "",
                          "value": "Runtime"
                        }
                      ],
                      "functionName": {
                        "name": "datasize",
                        "nativeSrc": "190:8:0",
                        "nodeType": "YulIdentifier",
                        "src": "190:8:0"
                      },
                      "nativeSrc": "190:19:0",
                      "nodeType": "YulFunctionCall",
                      "src": "190:19:0"
                    }
                  ],
                  "functionName": {
                    "name": "datacopy",
                    "nativeSrc": "155:8:0",
                    "nodeType": "YulIdentifier",
                    "src": "155:8:0"
                  },
                  "nativeSrc": "155:55:0",
                  "nodeType": "YulFunctionCall",
                  "src": "155:55:0"
                },
                "nativeSrc": "155:55:0",
                "nodeType": "YulExpressionStatement",
                "src": "155:55:0"
              },
              {
                "expression": {
                  "arguments": [
                    {
                      "kind": "number",
                      "nativeSrc": "220:1:0",
                      "nodeType": "YulLiteral",
                      "src": "220:1:0",
                      "type": "",
                      "value": "0"
                    },
                    {
                      "arguments": [
                        {
                          "hexValue": "52756e74696d65",
                          "kind": "string",
                          "nativeSrc": "232:9:0",
                          "nodeType": "YulLiteral",
                          "src": "232:9:0",
                          "type": "",
                          "value": "Runtime"
                        }
                      ],
                      "functionName": {
                        "name": "datasize",
                        "nativeSrc": "223:8:0",
                        "nodeType": "YulIdentifier",
                        "src": "223:8:0"
                      },
                      "nativeSrc": "223:19:0",
                      "nodeType": "YulFunctionCall",
                      "src": "223:19:0"
                    }
                  ],
                  "functionName": {
                    "name": "return",
                    "nativeSrc": "213:6:0",
                    "nodeType": "YulIdentifier",
                    "src": "213:6:0"
                  },
                  "nativeSrc": "213:30:0",
                  "nodeType": "YulFunctionCall",
                  "src": "213:30:0"
                },
                "nativeSrc": "213:30:0",
                "nodeType": "YulExpressionStatement",
                "src": "213:30:0"
              }
            ]
          },
          "nodeType": "YulCode"
        },
        "name": "SimpleYul",
        "nodeType": "YulObject",
        "subObjects": [
          {
            "code": {
              "block": {
                "nativeSrc": "274:451:0",
                "nodeType": "YulBlock",
                "src": "274:451:0",
                "statements": [
                  {
                    "nativeSrc": "321:41:0",
                    "nodeType": "YulVariableDeclaration",
                    "src": "321:41:0",
                    "value": {
                      "arguments": [
                        {
                          "kind": "number",
                          "nativeSrc": "341:3:0",
                          "nodeType": "YulLiteral",
                          "src": "341:3:0",
                          "type": "",
                          "value": "224"
                        },
                        {
                          "arguments": [
                            {
                              "kind": "number",
                              "nativeSrc": "359:1:0",
                              "nodeType": "YulLiteral",
                              "src": "359:1:0",
                              "type": "",
                              "value": "0"
                            }
                          ],
                          "functionName": {
                            "name": "calldataload",
                            "nativeSrc": "346:12:0",
                            "nodeType": "YulIdentifier",
                            "src": "346:12:0"
                          },
                          "nativeSrc": "346:15:0",
                          "nodeType": "YulFunctionCall",
                          "src": "346:15:0"
                        }
                      ],
                      "functionName": {
                        "name": "shr",
                        "nativeSrc": "337:3:0",
                        "nodeType": "YulIdentifier",
                        "src": "337:3:0"
                      },
                      "nativeSrc": "337:25:0",
                      "nodeType": "YulFunctionCall",
                      "src": "337:25:0"
                    },
                    "variables": [
                      {
                        "name": "selector",
                        "nativeSrc": "325:8:0",
                        "nodeType": "YulTypedName",
                        "src": "325:8:0",
                        "type": ""
                      }
                    ]
                  },
                  {
                    "cases": [
                      {
                        "body": {
                          "nativeSrc": "449:66:0",
                          "nodeType": "YulBlock",
                          "src": "449:66:0",
                          "statements": [
                            {
                              "nativeSrc": "455:31:0",
                              "nodeType": "YulVariableDeclaration",
                              "src": "455:31:0",
                              "value": {
                                "arguments": [
                                  {
                                    "kind": "number",
                                    "nativeSrc": "484:1:0",
                                    "nodeType": "YulLiteral",
                                    "src": "484:1:0",
                                    "type": "",
                                    "value": "4"
                                  }
                                ],
                                "functionName": {
                                  "name": "calldataload",
                                  "nativeSrc": "471:12:0",
                                  "nodeType": "YulIdentifier",
                                  "src": "471:12:0"
                                },
                                "nativeSrc": "471:15:0",
                                "nodeType": "YulFunctionCall",
                                "src": "471:15:0"
                              },
                              "variables": [
                                {
                                  "name": "newValue",
                                  "nativeSrc": "459:8:0",
                                  "nodeType": "YulTypedName",
                                  "src": "459:8:0",
                                  "type": ""
                                }
                              ]
                            },
                            {
                              "expression": {
                                "arguments": [
                                  {
                                    "kind": "number",
                                    "nativeSrc": "498:1:0",
                                    "nodeType": "YulLiteral",
                                    "src": "498:1:0",
                                    "type": "",
                                    "value": "0"
                                  },
                                  {
                                    "name": "newValue",
                                    "nativeSrc": "501:8:0",
                                    "nodeType": "YulIdentifier",
                                    "src": "501:8:0"
                                  }
                                ],
                                "functionName": {
                                  "name": "sstore",
                                  "nativeSrc": "491:6:0",
                                  "nodeType": "YulIdentifier",
                                  "src": "491:6:0"
                                },
                                "nativeSrc": "491:19:0",
                                "nodeType": "YulFunctionCall",
                                "src": "491:19:0"
                              },
                              "nativeSrc": "491:19:0",
                              "nodeType": "YulExpressionStatement",
                              "src": "491:19:0"
                            }
                          ]
                        },
                        "nativeSrc": "433:82:0",
                        "nodeType": "YulCase",
                        "src": "433:82:0",
                        "value": {
                          "kind": "number",
                          "nativeSrc": "438:10:0",
                          "nodeType": "YulLiteral",
                          "src": "438:10:0",
                          "type": "",
                          "value": "0x55241077"
                        }
                      },
                      {
                        "body": {
                          "nativeSrc": "575:83:0",
                          "nodeType": "YulBlock",
                          "src": "575:83:0",
                          "statements": [
                            {
                              "nativeSrc": "581:27:0",
                              "nodeType": "YulVariableDeclaration",
                              "src": "581:27:0",
                              "value": {
                                "arguments": [
                                  {
                                    "kind": "number",
                                    "nativeSrc": "606:1:0",
                                    "nodeType": "YulLiteral",
                                    "src": "606:1:0",
                                    "type": "",
                                    "value": "0"
                                  }
                                ],
                                "functionName": {
                                  "name": "sload",
                                  "nativeSrc": "600:5:0",
                                  "nodeType": "YulIdentifier",
                                  "src": "600:5:0"
                                },
                                "nativeSrc": "600:8:0",
                                "nodeType": "YulFunctionCall",
                                "src": "600:8:0"
                              },
                              "variables": [
                                {
                                  "name": "storedValue",
                                  "nativeSrc": "585:11:0",
                                  "nodeType": "YulTypedName",
                                  "src": "585:11:0",
                                  "type": ""
                                }
                              ]
                            },
                            {
                              "expression": {
                                "arguments": [
                                  {
                                    "kind": "number",
                                    "nativeSrc": "620:1:0",
                                    "nodeType": "YulLiteral",
                                    "src": "620:1:0",
                                    "type": "",
                                    "value": "0"
                                  },
                                  {
                                    "name": "storedValue",
                                    "nativeSrc": "623:11:0",
                                    "nodeType": "YulIdentifier",
                                    "src": "623:11:0"
                                  }
                                ],
                                "functionName": {
                                  "name": "mstore",
                                  "nativeSrc": "613:6:0",
                                  "nodeType": "YulIdentifier",
                                  "src": "613:6:0"
                                },
                                "nativeSrc": "613:22:0",
                                "nodeType": "YulFunctionCall",
                                "src": "613:22:0"
                              },
                              "nativeSrc": "613:22:0",
                              "nodeType": "YulExpressionStatement",
                              "src": "613:22:0"
                            },
                            {
                              "expression": {
                                "arguments": [
                                  {
                                    "kind": "number",
                                    "nativeSrc": "647:1:0",
                                    "nodeType": "YulLiteral",
                                    "src": "647:1:0",
                                    "type": "",
                                    "value": "0"
                                  },
                                  {
                                    "kind": "number",
                                    "nativeSrc": "650:2:0",
                                    "nodeType": "YulLiteral",
                                    "src": "650:2:0",
                                    "type": "",
                                    "value": "32"
                                  }
                                ],
                                "functionName": {
                                  "name": "return",
                                  "nativeSrc": "640:6:0",
                                  "nodeType": "YulIdentifier",
                                  "src": "640:6:0"
                                },
                                "nativeSrc": "640:13:0",
                                "nodeType": "YulFunctionCall",
                                "src": "640:13:0"
                              },
                              "nativeSrc": "640:13:0",
                              "nodeType": "YulExpressionStatement",
                              "src": "640:13:0"
                            }
                          ]
                        },
                        "nativeSrc": "559:99:0",
                        "nodeType": "YulCase",
                        "src": "559:99:0",
                        "value": {
                          "kind": "number",
                          "nativeSrc": "564:10:0",
                          "nodeType": "YulLiteral",
                          "src": "564:10:0",
                          "type": "",
                          "value": "0x20965255"
                        }
                      },
                      {
                        "body": {
                          "nativeSrc": "698:23:0",
                          "nodeType": "YulBlock",
                          "src": "698:23:0",
                          "statements": [
                            {
                              "expression": {
                                "arguments": [
                                  {
                                    "kind": "number",
                                    "nativeSrc": "711:1:0",
                                    "nodeType": "YulLiteral",
                                    "src": "711:1:0",
                                    "type": "",
                                    "value": "0"
                                  },
                                  {
                                    "kind": "number",
                                    "nativeSrc": "714:1:0",
                                    "nodeType": "YulLiteral",
                                    "src": "714:1:0",
                                    "type": "",
                                    "value": "0"
                                  }
                                ],
                                "functionName": {
                                  "name": "revert",
                                  "nativeSrc": "704:6:0",
                                  "nodeType": "YulIdentifier",
                                  "src": "704:6:0"
                                },
                                "nativeSrc": "704:12:0",
                                "nodeType": "YulFunctionCall",
                                "src": "704:12:0"
                              },
                              "nativeSrc": "704:12:0",
                              "nodeType": "YulExpressionStatement",
                              "src": "704:12:0"
                            }
                          ]
                        },
                        "nativeSrc": "690:31:0",
                        "nodeType": "YulCase",
                        "src": "690:31:0",
                        "value": "default"
                      }
                    ],
                    "expression": {
                      "name": "selector",
                      "nativeSrc": "374:8:0",
                      "nodeType": "YulIdentifier",
                      "src": "374:8:0"
                    },
                    "nativeSrc": "367:354:0",
                    "nodeType": "YulSwitch",
                    "src": "367:354:0"
                  }
                ]
              },
              "nodeType": "YulCode"
            },
            "name": "Runtime",
            "nodeType": "YulObject",
            "subObjects": []
          }
        ]
      },
      "id": 0
    }
  }
}

export default solcOutput
