
[package]
name = 'my_rust_node_lib'
version = '0.1.0'
edition = '2021'

[dependencies]
napi = { version = '2.10.2', default-features = false, features = [
	'napi4',
] }
napi-derive = '2.9.3'

[lib]
crate-type = [
	'cdylib',
]

[build-dependencies]
napi-build = '2.0.1'
