export {
createBaseClient,
prefundedAccounts,
GENESIS_STATE,
type Hardfork,
type Extension,
type BaseClient,
type CustomPrecompile,
type BaseClientOptions,
type AutoMining,
type ManualMining,
type MiningConfig,
type IntervalMining,
type Filter,
type FilterType,
type ProviderConnectInfo,
type EIP1193EventEmitter,
ProviderRpcError,
type ProviderMessage,
type EIP1193EventMap,
type EIP1193Events,
} from "@tevm/base-client";
