export {
  createBaseClient,
  prefundedAccounts,
  GENESIS_STATE,
  type Hardfork,
  type Extension,
  type BaseClient,
  type CustomPrecompile,
  type BaseClientOptions,
  type AutoMining,
  type ManualMining,
  type MiningConfig,
  type IntervalMining,
  type Filter,
  type FilterType,
} from "@tevm/base-client";
