version: '3'

services:
  resolutions-test:
    image: node:18-alpine
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    working_dir: /app
    command: /bin/sh -c "cd resolutions-test && npm install && npm run test:with-cli"
    depends_on:
      - go-builder

  go-builder:
    image: golang:1.19-alpine
    volumes:
      - .:/app
    working_dir: /app
    command: /bin/sh -c "cd resolutions-go && go build -o bin/cli cmd/cli/main.go"

volumes:
  node_modules: