services:
  tevm-build:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: tevm-monorepo-build
    environment:
      - TEVM_RPC_URLS_MAINNET=${TEVM_RPC_URLS_MAINNET:-}
      - TEVM_RPC_URLS_OPTIMISM=${TEVM_RPC_URLS_OPTIMISM:-}
      - DOCKER_BUILDKIT=1
      - BUILDKIT_PROGRESS=plain
    volumes:
      # Mount build cache to persist between runs
      - pnpm-store:/pnpm/store
      - cargo-cache:/root/.cargo
      - zig-cache:/root/.cache/zig
      # Mount dist and build outputs if needed
      - ./dist:/app/dist
      - ./packages:/app/packages
      - ./bundler-packages:/app/bundler-packages
    working_dir: /app
    # Skip Zig build and run the rest of the build
    command: ["sh", "-c", "bun x concurrently 'pnpm i' 'bun lint' 'bun sort-package-json' && nx run-many --targets=generate:docs,build:types,typecheck,test:coverage,build:dist,dev:run,build:app,lint:package,lint:deps,lint,format,build:rust:lib,build:wasm --parallel=2"]
    # Allocate more resources for the build
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G
        reservations:
          cpus: '2'
          memory: 4G

volumes:
  pnpm-store:
  cargo-cache:
  zig-cache: