packages:
  - "bundler-packages/*"
  - "bundler"
  - "configs/*"
  - "docs"
  - "examples/*"
  - "experimental/*"
  - "extensions/*"
  - "lsp/*"
  - "packages/*"
  - 'scripts'
  - 'tevm'
  - "test/*"
