packages:
  - bundler-packages/*
  - bundler
  - cli
  - configs/*
  - docs/*
  - examples/*
  - experimental/*
  - extensions/*
  - lsp/*
  - packages/*
  - scripts
  - tevm
  - test/*
onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@swc/core'
  - bufferutil
  - bun
  - esbuild
  - fsevents
  - keccak
  - nx
  - secp256k1
  - sharp
  - utf-8-validate
  - wasm-pack
