packages:
  - bundler-packages/*
  - bundler-packages/resolutions-rs/npm/*
  - bundler-packages/runtime-rs/npm/*
  - bundler
  - configs/*
  - cli
  - docs/*
  - examples/*
  - extensions/*
  - lib/*
  - lsp/*
  - packages/*
  - scripts
  - src
  - src/ui
  - tevm
  - test/*
onlyBuiltDependencies:
  - "@biomejs/biome"
  - "@swc/core"
  - bufferutil
  - bun
  - esbuild
  - fsevents
  - keccak
  - nx
  - secp256k1
  - sharp
  - utf-8-validate
  - wasm-pack
