packages:
  - "bundlers/*"
  - "blockexplorer"
  - "cli"
  - "config"
  - "core"
  - "blockexplorer"
  - "docs"
  - "e2e"
  - "effect"
  - "ethers"
  - "examples/*"
  - "experimental/*"
  - "runtime"
  - "schemas"
  - "revm"
  - "resolutions"
  - "schemas"
  - "solc"
  - "state"
  - "ts-plugin"
  - "tsconfig"
  - "viem-effect"

