packages:
  - "bundlers/*"
  - "bundlers/webpack"
  - "cli"
  - "config"
  - "core"
  - "docs"
  - "e2e"
  - "ethers"
  - "examples/*"
  - "language-server"
  - "ts-plugin"
  - "tsconfig"
  - "vscode"

