packages:
  - "bundler-packages/*"
  - "bundler"
  - "cli"
  - "configs/*"
  - "docs/*"
  - "examples/*"
  - "experimental/*"
  - "extensions/*"
  - "lsp/*"
  - "packages/*"
  - "scripts"
  - "tevm"
  - "test/*"
