/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface JsModuleInfo {
  code: string
  importedIds: Array<string>
}

export interface JsResolvedImport {
  original: string
  absolute: string
  updated: string
}

export declare export declare function processModuleJs(filePath: string, code: string, remappings?: Record<string, string> | undefined | null, libs?: Array<string> | undefined | null): Promise<JsModuleInfo>

export declare export declare function resolveImportsJs(filePath: string, code: string, remappings?: Record<string, string> | undefined | null, libs?: Array<string> | undefined | null): Promise<Array<JsResolvedImport>>
