/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface JsModuleInfo {
  code: string;
  importedIds: Array<string>;
}

export interface JsResolvedImport {
  original: string;
  absolute: string;
  updated: string;
}

/**
 * Type for a complete module in the moduleFactory result map
 */
export interface JsModule {
  id: string;
  code: string;
  rawCode: string;
  importedIds: Array<string>;
}

export declare function resolveImportsJs(
  filePath: string,
  code: string,
  remappings?: Record<string, string> | undefined | null,
  libs?: Array<string> | undefined | null,
): Promise<Array<JsResolvedImport>>;

/**
 * Processes a module and all its dependencies to create a complete module map
 * @param filePath The absolute path to the Solidity file
 * @param code The Solidity code
 * @param remappings Remappings for import paths
 * @param libs Libraries to include in the resolution
 * @returns A map where keys are file paths and values are module objects
 */
export declare function moduleFactoryJs(
  filePath: string,
  code: string,
  remappings?: Record<string, string> | undefined | null,
  libs?: Array<string> | undefined | null,
): Promise<Map<string, JsModule>>;
