[package]
name = "tevm_evm_rs"
version = "0.1.0"
description = "Rust implementation of tevm EVM for WASM using REVM"
edition = "2021"
repository = "https://github.com/evmts/tevm-monorepo"
license = "MIT"
keywords = ["ethereum", "evm", "tevm", "wasm", "revm"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.87"
js-sys = "0.3.64"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde-wasm-bindgen = "0.5.0"
once_cell = "1.17.1"
console_error_panic_hook = "0.1.7"
hex = "0.4.3"

# REVM dependencies
revm = { version = "3.5.0", features = ["memory_db", "std"] }