[package]
name = "evm-rs"
version = "0.1.0"
edition = "2021"
authors = ["Tevm Team"]
description = "Rust EVM implementation for Tevm with WASM bindings"
license = "MIT"
repository = "https://github.com/evmts/tevm-monorepo"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.91"

# The `console_error_panic_hook` crate provides better debugging of panics when
# in browsers, but only include it when debugging.
console_error_panic_hook = { version = "0.1.7", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.41"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true

# Don't include std in the wasm output
[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-Oz", "--enable-mutable-globals"]