[profile.default]
src = 'src'
out = 'artifacts'
lib = 'lib'
test = 'src'
no_match_test = "FFI|LongRunning"
optimizer = true
optimizer_runs = 1000000
bytecode_hash = "none"

solc = "0.8.17"

allow_paths = ["../node_modules"]
remappings = [
  '@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/',
]
[rpc_endpoints]
mainnet = "${RPC_URL_MAINNET}"
goerli = "${RPC_URL_GOERLI}"
optimism = "${RPC_URL_OPTIMISM}"
arbitrum = "${RPC_URL_ARBITRUM}"
polygon = "${RPC_URL_POLYGON}"

[etherscan]
mainnet = {key = "${ETHERSCAN_KEY}"}
goerli = {key = "${ETHERSCAN_KEY}", url = "https://api-goerli.etherscan.io/api"}
optimism = {key = "${OPTIMISM_ETHERSCAN_KEY}", url = "https://api-optimistic.etherscan.io/api"}
arbitrum = {key = "${ARBISCAN_KEY}", url = "https://api.arbiscan.io/api"}
polygon = {key = "${POLYGONSCAN_KEY}", url = "https://api.polygonscan.com/api"}

[profile.intense]
no_match_test = "FFI"

[profile.intense.fuzz]
runs = 10000

[profile.ffi]
ffi = true
no_match_test = "LongRunning"