[profile.default]
# Keep this version in sync with package.json and evmts.config.ts
solc = "0.8.19"
src = "src/contracts"
test = "test"
out = "artifacts"
lib = ["node_modules", "../../node_modules", "lib"]

allow_paths = ["../../node_modules"]

