# Load plugin including EVMts plugin
# EVMts is configured in the tsconfig.json
# in future it will be configured via evmts.config.ts
preload = ["./plugins.ts"]

# Use plugin in tests too
[test]
preload = ["./plugins.ts"]

