// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { abstractTestnet as _abstractTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Abstract Testnet (chain ID 11124). Explorer: https://sepolia.abscan.org. Default RPC: https://api.testnet.abs.xyz.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const abstractTestnet = createCommon({
	..._abstractTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
