// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { ancient8 as _ancient8 } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Ancient8 (chain ID 888888888). Explorer: https://scan.ancient8.gg. Default RPC: https://rpc.ancient8.gg.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const ancient8 = createCommon({
	..._ancient8,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
