// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { anvil as _anvil } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Anvil (chain ID 31337). Explorer: —. Default RPC: http://127.0.0.1:8545.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const anvil = createCommon({
	..._anvil,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
