// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { arbitrumNova as _arbitrumNova } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Arbitrum Nova (chain ID 42170). Explorer: https://nova.arbiscan.io. Default RPC: https://nova.arbitrum.io/rpc.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const arbitrumNova = createCommon({
	..._arbitrumNova,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
