// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { arbitrumSepolia as _arbitrumSepolia } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Arbitrum Sepolia (chain ID 421614). Explorer: https://sepolia.arbiscan.io. Default RPC: https://sepolia-rollup.arbitrum.io/rpc.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const arbitrumSepolia = createCommon({
	..._arbitrumSepolia,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
