// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { arbitrum as _arbitrum } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Arbitrum One (chain ID 42161). Explorer: https://arbiscan.io. Default RPC: https://arb1.arbitrum.io/rpc.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const arbitrum = createCommon({
	..._arbitrum,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
