// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { arbitrumGoerli as _arbitrumGoerli } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Arbitrum Goerli (chain ID 421613). Explorer: https://goerli.arbiscan.io. Default RPC: https://goerli-rollup.arbitrum.io/rpc.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const arbitrumGoerli = createCommon({
	..._arbitrumGoerli,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
