// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { areonNetwork as _areonNetwork } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Areon Network (chain ID 463). Explorer: https://areonscan.com. Default RPC: https://mainnet-rpc.areon.network.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const areonNetwork = createCommon({
	..._areonNetwork,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
