// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { artelaTestnet as _artelaTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Artela Testnet (chain ID 11822). Explorer: https://betanet-scan.artela.network. Default RPC: https://betanet-rpc1.artela.network.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const artelaTestnet = createCommon({
	..._artelaTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
