// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { assetChainTestnet as _assetChainTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for AssetChain Testnet (chain ID 42421). Explorer: https://scan-testnet.assetchain.org. Default RPC: https://enugu-rpc.assetchain.org.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const assetChainTestnet = createCommon({
	..._assetChainTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
