// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { astarZkEVM as _astarZkEVM } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Astar zkEVM (chain ID 3776). Explorer: https://astar-zkevm.explorer.startale.com. Default RPC: https://rpc-zkevm.astar.network.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const astarZkEVM = createCommon({
	..._astarZkEVM,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
