// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { auroraTestnet as _auroraTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Aurora Testnet (chain ID 1313161555). Explorer: https://testnet.aurorascan.dev. Default RPC: https://testnet.aurora.dev.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const auroraTestnet = createCommon({
	..._auroraTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
