// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { auroria as _auroria } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Auroria Testnet (chain ID 205205). Explorer: https://auroria.explorer.stratisevm.com. Default RPC: https://auroria.rpc.stratisevm.com.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const auroria = createCommon({
	..._auroria,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
