// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { aurora as _aurora } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Aurora (chain ID 1313161554). Explorer: https://aurorascan.dev. Default RPC: https://mainnet.aurora.dev.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const aurora = createCommon({
	..._aurora,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
