// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { bahamut as _bahamut } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Bahamut (chain ID 5165). Explorer: https://www.ftnscan.com. Default RPC: https://rpc1.bahamut.io.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const bahamut = createCommon({
	..._bahamut,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
