// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { base as _base } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Base (chain ID 8453). Explorer: https://basescan.org. Default RPC: https://mainnet.base.org.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const base = createCommon({
	..._base,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
