// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { beamTestnet as _beamTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Beam Testnet (chain ID 13337). Explorer: https://subnets-test.avax.network/beam. Default RPC: https://build.onbeam.com/rpc/testnet.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const beamTestnet = createCommon({
	..._beamTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
