// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { beam as _beam } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Beam (chain ID 4337). Explorer: https://subnets.avax.network/beam. Default RPC: https://build.onbeam.com/rpc.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const beam = createCommon({
	..._beam,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
