// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { bearNetworkChainMainnet as _bearNetworkChainMainnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Bear Network Chain Mainnet (chain ID 641230). Explorer: https://brnkscan.bearnetwork.net. Default RPC: https://brnkc-mainnet.bearnetwork.net.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const bearNetworkChainMainnet = createCommon({
	..._bearNetworkChainMainnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
