// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { berachainTestnetbArtio as _berachainTestnetbArtio } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Berachain bArtio (chain ID 80084). Explorer: https://bartio.beratrail.io. Default RPC: https://bartio.rpc.berachain.com.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const berachainTestnetbArtio = createCommon({
	..._berachainTestnetbArtio,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
