// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { bevmMainnet as _bevmMainnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for BEVM Mainnet (chain ID 11501). Explorer: https://scan-mainnet.bevm.io. Default RPC: https://rpc-mainnet-1.bevm.io.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const bevmMainnet = createCommon({
	..._bevmMainnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
