// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { bitkubTestnet as _bitkubTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Bitkub Testnet (chain ID 25925). Explorer: https://testnet.bkcscan.com. Default RPC: https://rpc-testnet.bitkubchain.io.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const bitkubTestnet = createCommon({
	..._bitkubTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
