// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { bitTorrentTestnet as _bitTorrentTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for BitTorrent Chain Testnet (chain ID 1028). Explorer: https://testnet.bttcscan.com. Default RPC: https://testrpc.bittorrentchain.io.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const bitTorrentTestnet = createCommon({
	..._bitTorrentTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
