// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { blast as _blast } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Blast (chain ID 81457). Explorer: https://blastscan.io. Default RPC: https://rpc.blast.io.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const blast = createCommon({
	..._blast,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
