// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { blastSepolia as _blastSepolia } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Blast Sepolia (chain ID 168587773). Explorer: https://sepolia.blastscan.io. Default RPC: https://sepolia.blast.io.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const blastSepolia = createCommon({
	..._blastSepolia,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
