// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { boba as _boba } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Boba Network (chain ID 288). Explorer: https://bobascan.com. Default RPC: https://mainnet.boba.network.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const boba = createCommon({
	..._boba,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
