// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { bobaSepolia as _bobaSepolia } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Boba Sepolia (chain ID 28882). Explorer: https://testnet.bobascan.com. Default RPC: https://sepolia.boba.network.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const bobaSepolia = createCommon({
	..._bobaSepolia,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
