// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { botanixTestnet as _botanixTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Botanix Testnet (chain ID 3636). Explorer: https://testnet.botanixscan.io. Default RPC: https://node.botanixlabs.dev.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const botanixTestnet = createCommon({
	..._botanixTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
