// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { bronosTestnet as _bronosTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Bronos Testnet (chain ID 1038). Explorer: https://tbroscan.bronos.org. Default RPC: https://evm-testnet.bronos.org.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const bronosTestnet = createCommon({
	..._bronosTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
