// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { bronos as _bronos } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Bronos (chain ID 1039). Explorer: https://broscan.bronos.org. Default RPC: https://evm.bronos.org.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const bronos = createCommon({
	..._bronos,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
