// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { bscGreenfield as _bscGreenfield } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for BNB Greenfield Chain (chain ID 1017). Explorer: https://greenfieldscan.com. Default RPC: https://greenfield-chain.bnbchain.org.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const bscGreenfield = createCommon({
	..._bscGreenfield,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
