// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { btrTestnet as _btrTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Bitlayer Testnet (chain ID 200810). Explorer: https://testnet.btrscan.com. Default RPC: https://testnet-rpc.bitlayer.org.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const btrTestnet = createCommon({
	..._btrTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
