// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { bxn as _bxn } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for BlackFort Exchange Network (chain ID 4999). Explorer: https://explorer.blackfort.network. Default RPC: https://mainnet.blackfort.network/rpc.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const bxn = createCommon({
	..._bxn,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
