// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { canto as _canto } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Canto (chain ID 7700). Explorer: https://tuber.build. Default RPC: https://canto.gravitychain.io.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const canto = createCommon({
	..._canto,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
