// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { celo as _celo } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Celo (chain ID 42220). Explorer: https://celoscan.io. Default RPC: https://forno.celo.org.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const celo = createCommon({
	..._celo,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
