// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { chiliz as _chiliz } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Chiliz Chain (chain ID 88888). Explorer: https://scan.chiliz.com. Default RPC: https://rpc.chiliz.com.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const chiliz = createCommon({
	..._chiliz,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
