// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { chips as _chips } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Chips Network (chain ID 2882). Explorer: —. Default RPC: https://node.chips.ooo/wasp/api/v1/chains/iota1pp3d3mnap3ufmgqnjsnw344sqmf5svjh26y2khnmc89sv6788y3r207a8fn/evm.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const chips = createCommon({
	..._chips,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
