// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { classic as _classic } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Ethereum Classic (chain ID 61). Explorer: https://blockscout.com/etc/mainnet. Default RPC: https://etc.rivet.link.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const classic = createCommon({
	..._classic,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
