// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { coreDao as _coreDao } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Core Dao (chain ID 1116). Explorer: https://scan.coredao.org. Default RPC: https://rpc.coredao.org.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const coreDao = createCommon({
	..._coreDao,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
