// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { cronoszkEVMTestnet as _cronoszkEVMTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Cronos zkEVM Testnet (chain ID 282). Explorer: https://explorer.zkevm.cronos.org/testnet. Default RPC: https://testnet.zkevm.cronos.org.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const cronoszkEVMTestnet = createCommon({
	..._cronoszkEVMTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
