// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { cronos as _cronos } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Cronos Mainnet (chain ID 25). Explorer: https://explorer.cronos.org. Default RPC: https://evm.cronos.org.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const cronos = createCommon({
	..._cronos,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
