// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { cronosTestnet as _cronosTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Cronos Testnet (chain ID 338). Explorer: https://explorer.cronos.org/testnet. Default RPC: https://evm-t3.cronos.org.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const cronosTestnet = createCommon({
	..._cronosTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
