// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { cyberTestnet as _cyberTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Cyber Testnet (chain ID 111557560). Explorer: https://testnet.cyberscan.co. Default RPC: https://cyber-testnet.alt.technology.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const cyberTestnet = createCommon({
	..._cyberTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
