// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { dchain as _dchain } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Dchain (chain ID 2716446429837000). Explorer: https://dchain-2716446429837000-1.sagaexplorer.io. Default RPC: https://dchain-2716446429837000-1.jsonrpc.sagarpc.io.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const dchain = createCommon({
	..._dchain,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
