// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { defichainEvmTestnet as _defichainEvmTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for DeFiChain EVM Testnet (chain ID 1131). Explorer: https://meta.defiscan.live/?network=TestNet. Default RPC: https://eth.testnet.ocean.jellyfishsdk.com.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const defichainEvmTestnet = createCommon({
	..._defichainEvmTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
