// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { defichainEvm as _defichainEvm } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for DeFiChain EVM Mainnet (chain ID 1130). Explorer: https://meta.defiscan.live. Default RPC: https://eth.mainnet.ocean.jellyfishsdk.com.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const defichainEvm = createCommon({
	..._defichainEvm,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
