// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { degen as _degen } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Degen (chain ID 666666666). Explorer: https://explorer.degen.tips. Default RPC: https://rpc.degen.tips.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const degen = createCommon({
	..._degen,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
