// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { dfk as _dfk } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for DFK Chain (chain ID 53935). Explorer: https://subnets.avax.network/defi-kingdoms. Default RPC: https://subnets.avax.network/defi-kingdoms/dfk-chain/rpc.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const dfk = createCommon({
	..._dfk,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
