// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { dodochainTestnet as _dodochainTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for DODOchain Testnet (chain ID 53457). Explorer: https://testnet-scan.dodochain.com. Default RPC: https://dodochain-testnet.alt.technology.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const dodochainTestnet = createCommon({
	..._dodochainTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
