// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { dogechain as _dogechain } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Dogechain (chain ID 2000). Explorer: https://explorer.dogechain.dog. Default RPC: https://rpc.dogechain.dog.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const dogechain = createCommon({
	..._dogechain,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
