// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { dreyerxTestnet as _dreyerxTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for DreyerX Testnet (chain ID 23452). Explorer: https://testnet-scan.dreyerx.com. Default RPC: http://testnet-rpc.dreyerx.com.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const dreyerxTestnet = createCommon({
	..._dreyerxTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
