// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { edgewareTestnet as _edgewareTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Beresheet BereEVM Testnet (chain ID 2022). Explorer: https://testnet.edgscan.live. Default RPC: https://beresheet-evm.jelliedowl.net.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const edgewareTestnet = createCommon({
	..._edgewareTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
