// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { edgeless as _edgeless } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Edgeless Network (chain ID 2026). Explorer: https://explorer.edgeless.network. Default RPC: https://rpc.edgeless.network/http.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const edgeless = createCommon({
	..._edgeless,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
