// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { edgelessTestnet as _edgelessTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Edgeless Testnet (chain ID 202). Explorer: https://testnet.explorer.edgeless.network. Default RPC: https://edgeless-testnet.rpc.caldera.xyz/http.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const edgelessTestnet = createCommon({
	..._edgelessTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
