// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { eon as _eon } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Horizen EON (chain ID 7332). Explorer: https://eon-explorer.horizenlabs.io. Default RPC: https://eon-rpc.horizenlabs.io/ethv1.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const eon = createCommon({
	..._eon,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
