// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { eos as _eos } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for EOS EVM (chain ID 17777). Explorer: https://explorer.evm.eosnetwork.com. Default RPC: https://api.evm.eosnetwork.com.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const eos = createCommon({
	..._eos,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
