// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { eosTestnet as _eosTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for EOS EVM Testnet (chain ID 15557). Explorer: https://explorer.testnet.evm.eosnetwork.com. Default RPC: https://api.testnet.evm.eosnetwork.com.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const eosTestnet = createCommon({
	..._eosTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
