// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { etherlink as _etherlink } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Etherlink (chain ID 42793). Explorer: https://explorer.etherlink.com. Default RPC: https://node.mainnet.etherlink.com.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const etherlink = createCommon({
	..._etherlink,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
