// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { etherlinkTestnet as _etherlinkTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Etherlink Testnet (chain ID 128123). Explorer: https://testnet.explorer.etherlink.com. Default RPC: https://node.ghostnet.etherlink.com.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const etherlinkTestnet = createCommon({
	..._etherlinkTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
