// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { evmos as _evmos } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Evmos (chain ID 9001). Explorer: https://escan.live. Default RPC: https://eth.bd.evmos.org:8545.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const evmos = createCommon({
	..._evmos,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
