// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { evmosTestnet as _evmosTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Evmos Testnet (chain ID 9000). Explorer: https://evm.evmos.dev/. Default RPC: https://eth.bd.evmos.dev:8545.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const evmosTestnet = createCommon({
	..._evmosTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
