// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { fantomTestnet as _fantomTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Fantom Testnet (chain ID 4002). Explorer: https://testnet.ftmscan.com. Default RPC: https://rpc.testnet.fantom.network.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const fantomTestnet = createCommon({
	..._fantomTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
