// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { fantomSonicTestnet as _fantomSonicTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Fantom Sonic Open Testnet (chain ID 64240). Explorer: https://public-sonic.fantom.network. Default RPC: https://rpcapi.sonic.fantom.network.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const fantomSonicTestnet = createCommon({
	..._fantomSonicTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
