// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { fibo as _fibo } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Fibo Chain (chain ID 12306). Explorer: https://scan.fibochain.org. Default RPC: https://network.hzroc.art.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const fibo = createCommon({
	..._fibo,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
