// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { flareTestnet as _flareTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Flare Testnet Coston2 (chain ID 114). Explorer: https://coston2-explorer.flare.network. Default RPC: https://coston2-api.flare.network/ext/C/rpc.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const flareTestnet = createCommon({
	..._flareTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
