// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { createCommon } from '../createCommon.js'
import { nativeDefineChain } from '@tevm/utils'

/**
 * Creates a common configuration for the flareTestnet chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 114
 * Chain Name: Coston2
 * Default Block Explorer: https://coston2-explorer.flare.network
 * Default RPC URL: https://coston2-api.flare.network/ext/C/rpc
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { flareTestnet } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: flareTestnet,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const flareTestnet = createCommon({
	...nativeDefineChain({
		id: 114,
		name: 'Flare Testnet Coston2',
		nativeCurrency: {
			decimals: 18,
			name: 'Coston2 Flare',
			symbol: 'C2FLR',
		},
		rpcUrls: {
			default: {
				http: ['https://coston2-api.flare.network/ext/C/rpc'],
			},
		},
		blockExplorers: {
			default: {
				name: 'Coston2 Explorer',
				url: 'https://coston2-explorer.flare.network',
				apiUrl: 'https://coston2-explorer.flare.network/api',
			},
		},
		testnet: true,
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
