// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { createCommon } from '../createCommon.js'
import { nativeDefineChain } from '@tevm/utils'

/**
 * Creates a common configuration for the flowPreviewnet chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 646
 * Chain Name: FlowEVM Previewnet
 * Default Block Explorer: https://previewnet.flowdiver.io
 * Default RPC URL: https://previewnet.evm.nodes.onflow.org
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { flowPreviewnet } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: flowPreviewnet,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const flowPreviewnet = createCommon({
	...nativeDefineChain({
		id: 646,
		name: 'Flow EVM Previewnet',
		nativeCurrency: {
			decimals: 18,
			name: 'Flow',
			symbol: 'FLOW',
		},
		rpcUrls: {
			default: {
				http: ['https://previewnet.evm.nodes.onflow.org'],
			},
		},
		blockExplorers: {
			default: {
				name: 'Previewnet Explorer',
				url: 'https://previewnet.flowdiver.io',
			},
		},
		contracts: {
			multicall3: {
				address: '0xca11bde05977b3631167028862be2a173976ca11',
				blockCreated: 6205,
			},
		},
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
