// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { flowTestnet as _flowTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Flow EVM Testnet (chain ID 545). Explorer: https://evm-testnet.flowscan.io. Default RPC: https://testnet.evm.nodes.onflow.org.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const flowTestnet = createCommon({
	..._flowTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
