// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { flowPreviewnet as _flowPreviewnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Flow EVM Previewnet (chain ID 646). Explorer: https://previewnet.flowdiver.io. Default RPC: https://previewnet.evm.nodes.onflow.org.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const flowPreviewnet = createCommon({
	..._flowPreviewnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
