// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { createCommon } from '../createCommon.js'
import { nativeDefineChain } from '@tevm/utils'

/**
 * Creates a common configuration for the flowTestnet chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 545
 * Chain Name: FlowEVM Testnet
 * Default Block Explorer: https://testnet.flowdiver.io
 * Default RPC URL: https://testnet.evm.nodes.onflow.org
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { flowTestnet } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: flowTestnet,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const flowTestnet = createCommon({
	...nativeDefineChain({
		id: 545,
		name: 'Flow EVM Testnet',
		nativeCurrency: {
			decimals: 18,
			name: 'Flow',
			symbol: 'FLOW',
		},
		rpcUrls: {
			default: {
				http: ['https://testnet.evm.nodes.onflow.org'],
			},
		},
		blockExplorers: {
			default: {
				name: 'Flow Diver',
				url: 'https://evm-testnet.flowscan.io',
			},
		},
		contracts: {
			multicall3: {
				address: '0xca11bde05977b3631167028862be2a173976ca11',
				blockCreated: 137518,
			},
		},
		testnet: true,
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
