// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { fluenceStage as _fluenceStage } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Fluence Stage (chain ID 123420000220). Explorer: https://blockscout.stage.fluence.dev. Default RPC: https://rpc.stage.fluence.dev.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const fluenceStage = createCommon({
	..._fluenceStage,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
