// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { fluence as _fluence } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Fluence (chain ID 9999999). Explorer: https://blockscout.mainnet.fluence.dev. Default RPC: https://rpc.mainnet.fluence.dev.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const fluence = createCommon({
	..._fluence,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
