// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { createCommon } from '../createCommon.js'
import { nativeDefineChain } from '@tevm/utils'

/**
 * Creates a common configuration for the fluence chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 9999999
 * Chain Name: Fluence
 * Default Block Explorer: https://blockscout.mainnet.fluence.dev
 * Default RPC URL: https://rpc.mainnet.fluence.dev
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { fluence } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: fluence,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const fluence = createCommon({
	...nativeDefineChain({
		id: 9999999,
		name: 'Fluence',
		nativeCurrency: {
			name: 'FLT',
			symbol: 'FLT',
			decimals: 18,
		},
		rpcUrls: {
			default: {
				http: ['https://rpc.mainnet.fluence.dev'],
				webSocket: ['wss://ws.mainnet.fluence.dev'],
			},
		},
		blockExplorers: {
			default: {
				name: 'Blockscout',
				url: 'https://blockscout.mainnet.fluence.dev',
				apiUrl: 'https://blockscout.mainnet.fluence.dev/api',
			},
		},
		contracts: {
			multicall3: {
				address: '0xcA11bde05977b3631167028862bE2a173976CA11',
				blockCreated: 207583,
			},
		},
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
