// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { forma as _forma } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Forma (chain ID 984122). Explorer: https://explorer.forma.art. Default RPC: https://rpc.forma.art.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const forma = createCommon({
	..._forma,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
