// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { fraxtalTestnet as _fraxtalTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Fraxtal Testnet (chain ID 2522). Explorer: https://holesky.fraxscan.com. Default RPC: https://rpc.testnet.frax.com.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const fraxtalTestnet = createCommon({
	..._fraxtalTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
