// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { nativeDefineChain } from '@tevm/utils'
import { createCommon } from '../createCommon.js'

/**
 * Creates a common configuration for the fraxtal chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 252
 * Chain Name: Fraxtal
 * Default Block Explorer: https://fraxscan.com
 * Default RPC URL: https://rpc.frax.com
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { fraxtal } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: fraxtal,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const fraxtal = createCommon({
	...nativeDefineChain({
		id: 252,
		name: 'Fraxtal',
		nativeCurrency: {
			decimals: 18,
			name: 'Frax Ether',
			symbol: 'frxETH',
		},
		rpcUrls: {
			default: {
				http: ['https://rpc.frax.com'],
			},
		},
		blockExplorers: {
			default: {
				name: 'Fraxscan',
				url: 'https://fraxscan.com',
			},
		},
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
