// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { funkiMainnet as _funkiMainnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Funki (chain ID 33979). Explorer: https://funkiscan.io. Default RPC: https://rpc-mainnet.funkichain.com.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const funkiMainnet = createCommon({
	..._funkiMainnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
