// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { fuse as _fuse } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Fuse (chain ID 122). Explorer: https://explorer.fuse.io. Default RPC: https://rpc.fuse.io.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const fuse = createCommon({
	..._fuse,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
