// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { fuseSparknet as _fuseSparknet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Fuse Sparknet (chain ID 123). Explorer: https://explorer.fusespark.io. Default RPC: https://rpc.fusespark.io.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const fuseSparknet = createCommon({
	..._fuseSparknet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
