// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { nativeDefineChain } from '@tevm/utils'
import { createCommon } from '../createCommon.js'

/**
 * Creates a common configuration for the fuse chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 122
 * Chain Name: Fuse
 * Default Block Explorer: https://explorer.fuse.io
 * Default RPC URL: https://rpc.fuse.io
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { fuse } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: fuse,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const fuse = createCommon({
	...nativeDefineChain({
		id: 122,
		name: 'Fuse',
		nativeCurrency: {
			decimals: 18,
			name: 'Fuse',
			symbol: 'FUSE',
		},
		rpcUrls: {
			default: {
				http: ['https://rpc.fuse.io'],
			},
		},
		blockExplorers: {
			default: {
				name: 'Fuse Explorer',
				url: 'https://explorer.fuse.io',
			},
		},
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
