// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { gnosis as _gnosis } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Gnosis (chain ID 100). Explorer: https://gnosisscan.io. Default RPC: https://rpc.gnosischain.com.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const gnosis = createCommon({
	..._gnosis,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
