// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { nativeDefineChain } from '@tevm/utils'
import { createCommon } from '../createCommon.js'

/**
 * Creates a common configuration for the gnosisChiado chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 10200
 * Chain Name: Gnosis Chiado
 * Default Block Explorer: https://blockscout.chiadochain.net
 * Default RPC URL: https://rpc.chiadochain.net
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { gnosisChiado } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: gnosisChiado,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const gnosisChiado = createCommon({
	...nativeDefineChain({
		id: 10200,
		name: 'Gnosis Chiado',
		nativeCurrency: {
			decimals: 18,
			name: 'Gnosis',
			symbol: 'xDAI',
		},
		rpcUrls: {
			default: {
				http: ['https://rpc.chiadochain.net'],
				webSocket: ['wss://rpc.chiadochain.net/wss'],
			},
		},
		blockExplorers: {
			default: {
				name: 'Blockscout',
				url: 'https://blockscout.chiadochain.net',
			},
		},
		testnet: true,
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
