// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { gnosisChiado as _gnosisChiado } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Gnosis Chiado (chain ID 10200). Explorer: https://blockscout.chiadochain.net. Default RPC: https://rpc.chiadochain.net.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const gnosisChiado = createCommon({
	..._gnosisChiado,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
