// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { gravity as _gravity } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Gravity Alpha Mainnet (chain ID 1625). Explorer: https://explorer.gravity.xyz. Default RPC: https://rpc.gravity.xyz.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const gravity = createCommon({
	..._gravity,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
