// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { ham as _ham } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Ham (chain ID 5112). Explorer: https://explorer.ham.fun. Default RPC: https://rpc.ham.fun.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const ham = createCommon({
	..._ham,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
