// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { haqqMainnet as _haqqMainnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for HAQQ Mainnet (chain ID 11235). Explorer: https://explorer.haqq.network. Default RPC: https://rpc.eth.haqq.network.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const haqqMainnet = createCommon({
	..._haqqMainnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
