// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { hashkeyTestnet as _hashkeyTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for HashKey Chain Testnet (chain ID 133). Explorer: https://testnet-explorer.hsk.xyz. Default RPC: https://testnet.hsk.xyz.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const hashkeyTestnet = createCommon({
	..._hashkeyTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
