// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { hederaTestnet as _hederaTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Hedera Testnet (chain ID 296). Explorer: https://hashscan.io/testnet. Default RPC: https://testnet.hashio.io/api.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const hederaTestnet = createCommon({
	..._hederaTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
