// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { immutableZkEvm as _immutableZkEvm } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Immutable zkEVM (chain ID 13371). Explorer: https://explorer.immutable.com. Default RPC: https://rpc.immutable.com.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const immutableZkEvm = createCommon({
	..._immutableZkEvm,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
