// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { nativeDefineChain } from '@tevm/utils'
import { createCommon } from '../createCommon.js'

/**
 * Creates a common configuration for the inEVM chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 2525
 * Chain Name: inEVM Mainnet
 * Default Block Explorer: https://inevm.calderaexplorer.xyz
 * Default RPC URL: https://mainnet.rpc.inevm.com/http
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { inEVM } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: inEVM,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const inEVM = createCommon({
	...nativeDefineChain({
		id: 2525,
		name: 'inEVM Mainnet',
		nativeCurrency: {
			name: 'Injective',
			symbol: 'INJ',
			decimals: 18,
		},
		rpcUrls: {
			default: {
				http: ['https://mainnet.rpc.inevm.com/http'],
			},
		},
		blockExplorers: {
			default: {
				name: 'inEVM Explorer',
				url: 'https://inevm.calderaexplorer.xyz',
				apiUrl: 'https://inevm.calderaexplorer.xyz/api/v2',
			},
		},
		contracts: {
			multicall3: {
				address: '0xca11bde05977b3631167028862be2a173976ca11',
				blockCreated: 118606,
			},
		},
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
