// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { iotaTestnet as _iotaTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for IOTA EVM Testnet (chain ID 1075). Explorer: https://explorer.evm.testnet.iotaledger.net. Default RPC: https://json-rpc.evm.testnet.iotaledger.net.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const iotaTestnet = createCommon({
	..._iotaTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
