// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { iota as _iota } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for IOTA EVM (chain ID 8822). Explorer: https://explorer.evm.iota.org. Default RPC: https://json-rpc.evm.iotaledger.net.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const iota = createCommon({
	..._iota,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
