// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { nativeDefineChain } from '@tevm/utils'
import { createCommon } from '../createCommon.js'

/**
 * Creates a common configuration for the iota chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 8822
 * Chain Name: IOTA EVM
 * Default Block Explorer: https://explorer.evm.iota.org
 * Default RPC URL: https://json-rpc.evm.iotaledger.net
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { iota } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: iota,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const iota = createCommon({
	...nativeDefineChain({
		id: 8822,
		name: 'IOTA EVM',
		network: 'iotaevm',
		nativeCurrency: {
			name: 'IOTA',
			symbol: 'IOTA',
			decimals: 18,
		},
		rpcUrls: {
			default: {
				http: ['https://json-rpc.evm.iotaledger.net'],
				webSocket: ['wss://ws.json-rpc.evm.iotaledger.net'],
			},
		},
		blockExplorers: {
			default: {
				name: 'Explorer',
				url: 'https://explorer.evm.iota.org',
				apiUrl: 'https://explorer.evm.iota.org/api',
			},
		},
		contracts: {
			multicall3: {
				address: '0xcA11bde05977b3631167028862bE2a173976CA11',
				blockCreated: 25022,
			},
		},
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
