// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { iotexTestnet as _iotexTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for IoTeX Testnet (chain ID 4690). Explorer: https://testnet.iotexscan.io. Default RPC: https://babel-api.testnet.iotex.io.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const iotexTestnet = createCommon({
	..._iotexTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
