// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { createCommon } from '../createCommon.js'
import { nativeDefineChain } from '@tevm/utils'

/**
 * Creates a common configuration for the iotex chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 4689
 * Chain Name: IoTeX
 * Default Block Explorer: https://iotexscan.io
 * Default RPC URL: https://babel-api.mainnet.iotex.io
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { iotex } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: iotex,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const iotex = createCommon({
	...nativeDefineChain({
		id: 4689,
		name: 'IoTeX',
		nativeCurrency: {
			decimals: 18,
			name: 'IoTeX',
			symbol: 'IOTX',
		},
		rpcUrls: {
			default: {
				http: ['https://babel-api.mainnet.iotex.io'],
				webSocket: ['wss://babel-api.mainnet.iotex.io'],
			},
		},
		blockExplorers: {
			default: {
				name: 'IoTeXScan',
				url: 'https://iotexscan.io',
			},
		},
		contracts: {
			multicall3: {
				address: '0xcA11bde05977b3631167028862bE2a173976CA11',
				blockCreated: 22163670,
			},
		},
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
