// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { iotex as _iotex } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for IoTeX (chain ID 4689). Explorer: https://iotexscan.io. Default RPC: https://babel-api.mainnet.iotex.io.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const iotex = createCommon({
	..._iotex,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
