// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { jbcTestnet as _jbcTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Jibchain Testnet (chain ID 88991). Explorer: https://exp.testnet.jibchain.net. Default RPC: https://rpc.testnet.jibchain.net.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const jbcTestnet = createCommon({
	..._jbcTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
