// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { createCommon } from '../createCommon.js'
import { nativeDefineChain } from '@tevm/utils'

/**
 * Creates a common configuration for the kaia chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 8217
 * Chain Name: Kaia
 * Default Block Explorer: https://kaiascope.com
 * Default RPC URL: https://public-en.node.kaia.io
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { kaia } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: kaia,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const kaia = createCommon({
	...nativeDefineChain({
		id: 8217,
		name: 'Kaia',
		nativeCurrency: {
			decimals: 18,
			name: 'Kaia',
			symbol: 'KAIA',
		},
		rpcUrls: {
			default: {
				http: ['https://public-en.node.kaia.io'],
			},
		},
		blockExplorers: {
			default: {
				name: 'KaiaScan',
				url: 'https://kaiascan.io',
				apiUrl: 'https://api-cypress.klaytnscope.com/api',
			},
		},
		contracts: {
			multicall3: {
				address: '0xcA11bde05977b3631167028862bE2a173976CA11',
				blockCreated: 96002415,
			},
		},
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
