// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { kakarotSepolia as _kakarotSepolia } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Kakarot Sepolia (chain ID 1802203764). Explorer: https://sepolia.kakarotscan.org. Default RPC: https://sepolia-rpc.kakarot.org.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const kakarotSepolia = createCommon({
	..._kakarotSepolia,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
