// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { createCommon } from '../createCommon.js'
import { nativeDefineChain } from '@tevm/utils'

/**
 * Creates a common configuration for the karura chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 686
 * Chain Name: Karura
 * Default Block Explorer: https://blockscout.karura.network
 * Default RPC URL: https://eth-rpc-karura.aca-api.network
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { karura } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: karura,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const karura = createCommon({
	...nativeDefineChain({
		id: 686,
		name: 'Karura',
		nativeCurrency: {
			name: 'Karura',
			symbol: 'KAR',
			decimals: 18,
		},
		rpcUrls: {
			default: {
				http: ['https://eth-rpc-karura.aca-api.network'],
				webSocket: ['wss://eth-rpc-karura.aca-api.network'],
			},
		},
		blockExplorers: {
			default: {
				name: 'Karura Blockscout',
				url: 'https://blockscout.karura.network',
				apiUrl: 'https://blockscout.karura.network/api',
			},
		},
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
