// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { karura as _karura } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Karura (chain ID 686). Explorer: https://blockscout.karura.network. Default RPC: https://eth-rpc-karura.aca-api.network.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const karura = createCommon({
	..._karura,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
