// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { kava as _kava } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Kava EVM (chain ID 2222). Explorer: https://kavascan.com. Default RPC: https://evm.kava.io.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const kava = createCommon({
	..._kava,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
