// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { kavaTestnet as _kavaTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Kava EVM Testnet (chain ID 2221). Explorer: https://testnet.kavascan.com/. Default RPC: https://evm.testnet.kava.io.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const kavaTestnet = createCommon({
	..._kavaTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
