// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { createCommon } from '../createCommon.js'
import { nativeDefineChain } from '@tevm/utils'

/**
 * Creates a common configuration for the kava chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 2222
 * Chain Name: Kava EVM
 * Default Block Explorer: https://kavascan.com
 * Default RPC URL: https://evm.kava.io
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { kava } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: kava,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const kava = createCommon({
	...nativeDefineChain({
		id: 2222,
		name: 'Kava EVM',
		nativeCurrency: {
			name: 'Kava',
			symbol: 'KAVA',
			decimals: 18,
		},
		rpcUrls: {
			default: {
				http: ['https://evm.kava.io'],
			},
		},
		blockExplorers: {
			default: {
				name: 'Kava EVM Explorer',
				url: 'https://kavascan.com',
				apiUrl: 'https://kavascan.com/api',
			},
		},
		contracts: {
			multicall3: {
				address: '0xca11bde05977b3631167028862be2a173976ca11',
				blockCreated: 3661165,
			},
		},
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
