// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { klaytn as _klaytn } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Klaytn (chain ID 8217). Explorer: https://scope.klaytn.com. Default RPC: https://public-en-cypress.klaytn.net.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const klaytn = createCommon({
	..._klaytn,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
