// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { nativeDefineChain } from '@tevm/utils'
import { createCommon } from '../createCommon.js'

/**
 * Creates a common configuration for the koi chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 701
 * Chain Name: Koi Network
 * Default Block Explorer: https://koi-scan.darwinia.network
 * Default RPC URL: https://koi-rpc.darwinia.network
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { koi } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: koi,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const koi = createCommon({
	...nativeDefineChain({
		id: 701,
		name: 'Koi Network',
		nativeCurrency: {
			decimals: 18,
			name: 'Koi Network Native Token',
			symbol: 'KRING',
		},
		rpcUrls: {
			default: {
				http: ['https://koi-rpc.darwinia.network'],
				webSocket: ['wss://koi-rpc.darwinia.network'],
			},
		},
		blockExplorers: {
			default: {
				name: 'Blockscout',
				url: 'https://koi-scan.darwinia.network',
			},
		},
		contracts: {
			multicall3: {
				address: '0xca11bde05977b3631167028862be2a173976ca11',
				blockCreated: 180001,
			},
		},
		testnet: true,
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
