// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { nativeDefineChain } from '@tevm/utils'
import { createCommon } from '../createCommon.js'

/**
 * Creates a common configuration for the kromaSepolia chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 2358
 * Chain Name: Kroma Sepolia
 * Default Block Explorer: https://blockscout.sepolia.kroma.network
 * Default RPC URL: https://api.sepolia.kroma.network
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { kromaSepolia } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: kromaSepolia,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const kromaSepolia = createCommon({
	...nativeDefineChain({
		id: 2358,
		name: 'Kroma Sepolia',
		nativeCurrency: {
			name: 'Sepolia Ether',
			symbol: 'ETH',
			decimals: 18,
		},
		rpcUrls: {
			default: {
				http: ['https://api.sepolia.kroma.network'],
			},
		},
		blockExplorers: {
			default: {
				name: 'Kroma Sepolia Explorer',
				url: 'https://blockscout.sepolia.kroma.network',
			},
		},
		testnet: true,
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
