// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { kroma as _kroma } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Kroma (chain ID 255). Explorer: https://blockscout.kroma.network. Default RPC: https://api.kroma.network.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const kroma = createCommon({
	..._kroma,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
