// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { l3x as _l3x } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for L3X Protocol (chain ID 12324). Explorer: https://explorer.l3x.com. Default RPC: https://rpc-mainnet.l3x.com.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const l3x = createCommon({
	..._l3x,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
