// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { l3xTestnet as _l3xTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for L3X Protocol Testnet (chain ID 12325). Explorer: https://explorer-testnet.l3x.com. Default RPC: https://rpc-testnet.l3x.com.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const l3xTestnet = createCommon({
	..._l3xTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
