// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { lightlinkPhoenix as _lightlinkPhoenix } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for LightLink Phoenix Mainnet (chain ID 1890). Explorer: https://phoenix.lightlink.io. Default RPC: https://replicator.phoenix.lightlink.io/rpc/v1.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const lightlinkPhoenix = createCommon({
	..._lightlinkPhoenix,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
