// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { nativeDefineChain } from '@tevm/utils'
import { createCommon } from '../createCommon.js'

/**
 * Creates a common configuration for the lightlinkPhoenix chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 1890
 * Chain Name: LightLink Phoenix Mainnet
 * Default Block Explorer: https://phoenix.lightlink.io
 * Default RPC URL: https://replicator.phoenix.lightlink.io/rpc/v1
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { lightlinkPhoenix } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: lightlinkPhoenix,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const lightlinkPhoenix = createCommon({
	...nativeDefineChain({
		id: 1890,
		name: 'LightLink Phoenix Mainnet',
		nativeCurrency: {
			name: 'Ether',
			symbol: 'ETH',
			decimals: 18,
		},
		rpcUrls: {
			default: {
				http: ['https://replicator.phoenix.lightlink.io/rpc/v1'],
			},
		},
		blockExplorers: {
			default: {
				name: 'LightLink Phoenix Explorer',
				url: 'https://phoenix.lightlink.io',
			},
		},
		contracts: {
			multicall3: {
				address: '0xcA11bde05977b3631167028862bE2a173976CA11',
				blockCreated: 125499184,
			},
		},
		testnet: false,
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
