// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { nativeDefineChain } from '@tevm/utils'
import { createCommon } from '../createCommon.js'

/**
 * Creates a common configuration for the lightlinkPegasus chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 1891
 * Chain Name: LightLink Pegasus Testnet
 * Default Block Explorer: https://pegasus.lightlink.io
 * Default RPC URL: https://replicator.pegasus.lightlink.io/rpc/v1
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { lightlinkPegasus } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: lightlinkPegasus,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const lightlinkPegasus = createCommon({
	...nativeDefineChain({
		id: 1891,
		name: 'LightLink Pegasus Testnet',
		nativeCurrency: {
			name: 'Ether',
			symbol: 'ETH',
			decimals: 18,
		},
		rpcUrls: {
			default: {
				http: ['https://replicator.pegasus.lightlink.io/rpc/v1'],
			},
		},
		blockExplorers: {
			default: {
				name: 'LightLink Pegasus Explorer',
				url: 'https://pegasus.lightlink.io',
			},
		},
		contracts: {
			multicall3: {
				address: '0xcA11bde05977b3631167028862bE2a173976CA11',
				blockCreated: 127188532,
			},
		},
		testnet: true,
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
