// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { lineaTestnet as _lineaTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Linea Goerli Testnet (chain ID 59140). Explorer: https://goerli.lineascan.build. Default RPC: https://rpc.goerli.linea.build.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const lineaTestnet = createCommon({
	..._lineaTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
