// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { linea as _linea } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Linea Mainnet (chain ID 59144). Explorer: https://lineascan.build. Default RPC: https://rpc.linea.build.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const linea = createCommon({
	..._linea,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
