// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { createCommon } from '../createCommon.js'
import { nativeDefineChain } from '@tevm/utils'

/**
 * Creates a common configuration for the lineaSepolia chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 59141
 * Chain Name: Linea Sepolia Testnet
 * Default Block Explorer: https://sepolia.lineascan.build
 * Default RPC URL: https://rpc.sepolia.linea.build
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { lineaSepolia } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: lineaSepolia,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const lineaSepolia = createCommon({
	...nativeDefineChain({
		id: 59141,
		name: 'Linea Sepolia Testnet',
		nativeCurrency: {
			name: 'Linea Ether',
			symbol: 'ETH',
			decimals: 18,
		},
		rpcUrls: {
			default: {
				http: ['https://rpc.sepolia.linea.build'],
				webSocket: ['wss://rpc.sepolia.linea.build'],
			},
		},
		blockExplorers: {
			default: {
				name: 'Etherscan',
				url: 'https://sepolia.lineascan.build',
				apiUrl: 'https://api-sepolia.lineascan.build/api',
			},
		},
		contracts: {
			multicall3: {
				address: '0xca11bde05977b3631167028862be2a173976ca11',
				blockCreated: 227427,
			},
			ensRegistry: {
				address: '0x5B2636F0f2137B4aE722C01dd5122D7d3e9541f7',
				blockCreated: 2395094,
			},
			ensUniversalResolver: {
				address: '0x4D41762915F83c76EcaF6776d9b08076aA32b492',
				blockCreated: 17168484,
			},
		},
		testnet: true,
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
