// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { lineaSepolia as _lineaSepolia } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Linea Sepolia Testnet (chain ID 59141). Explorer: https://sepolia.lineascan.build. Default RPC: https://rpc.sepolia.linea.build.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const lineaSepolia = createCommon({
	..._lineaSepolia,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
