// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { liskSepolia as _liskSepolia } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Lisk Sepolia (chain ID 4202). Explorer: https://sepolia-blockscout.lisk.com. Default RPC: https://rpc.sepolia-api.lisk.com.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const liskSepolia = createCommon({
	..._liskSepolia,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
