// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { luksoTestnet as _luksoTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for LUKSO Testnet (chain ID 4201). Explorer: https://explorer.execution.testnet.lukso.network. Default RPC: https://rpc.testnet.lukso.network.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const luksoTestnet = createCommon({
	..._luksoTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
