// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { createCommon } from '../createCommon.js'
import { nativeDefineChain } from '@tevm/utils'

/**
 * Creates a common configuration for the luksoTestnet chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 4201
 * Chain Name: LUKSO Testnet
 * Default Block Explorer: https://explorer.execution.testnet.lukso.network
 * Default RPC URL: https://rpc.testnet.lukso.network
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { luksoTestnet } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: luksoTestnet,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const luksoTestnet = createCommon({
	...nativeDefineChain({
		id: 4201,
		name: 'LUKSO Testnet',
		nativeCurrency: {
			name: 'LUKSO Testnet',
			symbol: 'LYXt',
			decimals: 18,
		},
		rpcUrls: {
			default: {
				http: ['https://rpc.testnet.lukso.network'],
				webSocket: ['wss://ws-rpc.testnet.lukso.network'],
			},
		},
		blockExplorers: {
			default: {
				name: 'LUKSO Testnet Explorer',
				url: 'https://explorer.execution.testnet.lukso.network',
				apiUrl: 'https://api.explorer.execution.testnet.lukso.network/api',
			},
		},
		contracts: {
			multicall3: {
				address: '0xcA11bde05977b3631167028862bE2a173976CA11',
				blockCreated: 605348,
			},
		},
		testnet: true,
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
