// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { createCommon } from '../createCommon.js'
import { nativeDefineChain } from '@tevm/utils'

/**
 * Creates a common configuration for the lyra chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 957
 * Chain Name: Lyra Chain
 * Default Block Explorer: https://explorer.lyra.finance
 * Default RPC URL: https://rpc.lyra.finance
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { lyra } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: lyra,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const lyra = createCommon({
	...nativeDefineChain({
		id: 957,
		name: 'Lyra Chain',
		nativeCurrency: {
			name: 'Ether',
			symbol: 'ETH',
			decimals: 18,
		},
		rpcUrls: {
			default: {
				http: ['https://rpc.lyra.finance'],
			},
		},
		blockExplorers: {
			default: {
				name: 'Lyra Explorer',
				url: 'https://explorer.lyra.finance',
				apiUrl: 'https://explorer.lyra.finance/api/v2',
			},
		},
		contracts: {
			multicall3: {
				address: '0xca11bde05977b3631167028862be2a173976ca11',
				blockCreated: 1935198,
			},
		},
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
