// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { mainnet as _mainnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Ethereum (chain ID 1). Explorer: https://etherscan.io. Default RPC: https://eth.merkle.io.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const mainnet = createCommon({
	..._mainnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
