// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { mandala as _mandala } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Mandala TC9 (chain ID 595). Explorer: https://blockscout.mandala.aca-staging.network. Default RPC: https://eth-rpc-tc9.aca-staging.network.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const mandala = createCommon({
	..._mandala,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
