// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { nativeDefineChain } from '@tevm/utils'
import { createCommon } from '../createCommon.js'

/**
 * Creates a common configuration for the mandala chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 595
 * Chain Name: Mandala TC9
 * Default Block Explorer: https://blockscout.mandala.aca-staging.network
 * Default RPC URL: https://eth-rpc-tc9.aca-staging.network
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { mandala } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: mandala,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const mandala = createCommon({
	...nativeDefineChain({
		id: 595,
		name: 'Mandala TC9',
		nativeCurrency: {
			name: 'Mandala',
			symbol: 'mACA',
			decimals: 18,
		},
		rpcUrls: {
			default: {
				http: ['https://eth-rpc-tc9.aca-staging.network'],
				webSocket: ['wss://eth-rpc-tc9.aca-staging.network'],
			},
		},
		blockExplorers: {
			default: {
				name: 'Mandala Blockscout',
				url: 'https://blockscout.mandala.aca-staging.network',
				apiUrl: 'https://blockscout.mandala.aca-staging.network/api',
			},
		},
		testnet: true,
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
