// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { manta as _manta } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Manta Pacific Mainnet (chain ID 169). Explorer: https://pacific-explorer.manta.network. Default RPC: https://pacific-rpc.manta.network/http.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const manta = createCommon({
	..._manta,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
