// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { mantle as _mantle } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Mantle (chain ID 5000). Explorer: https://mantlescan.xyz/. Default RPC: https://rpc.mantle.xyz.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const mantle = createCommon({
	..._mantle,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
