// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { mantaSepoliaTestnet as _mantaSepoliaTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Manta Pacific Sepolia Testnet (chain ID 3441006). Explorer: https://pacific-explorer.sepolia-testnet.manta.network. Default RPC: https://pacific-rpc.sepolia-testnet.manta.network/http.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const mantaSepoliaTestnet = createCommon({
	..._mantaSepoliaTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
