// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { nativeDefineChain } from '@tevm/utils'
import { createCommon } from '../createCommon.js'

/**
 * Creates a common configuration for the mantleTestnet chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 5001
 * Chain Name: Mantle Testnet
 * Default Block Explorer: https://explorer.testnet.mantle.xyz
 * Default RPC URL: https://rpc.testnet.mantle.xyz
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { mantleTestnet } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: mantleTestnet,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const mantleTestnet = createCommon({
	...nativeDefineChain({
		id: 5001,
		name: 'Mantle Testnet',
		nativeCurrency: {
			decimals: 18,
			name: 'MNT',
			symbol: 'MNT',
		},
		rpcUrls: {
			default: {
				http: ['https://rpc.testnet.mantle.xyz'],
			},
		},
		blockExplorers: {
			default: {
				name: 'Mantle Testnet Explorer',
				url: 'https://explorer.testnet.mantle.xyz',
				apiUrl: 'https://explorer.testnet.mantle.xyz/api',
			},
		},
		contracts: {
			multicall3: {
				address: '0xcA11bde05977b3631167028862bE2a173976CA11',
				blockCreated: 561333,
			},
		},
		testnet: true,
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
