// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { nativeDefineChain } from '@tevm/utils'
import { createCommon } from '../createCommon.js'

/**
 * Creates a common configuration for the mantaTestnet chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 3441005
 * Chain Name: Manta Pacific Testnet
 * Default Block Explorer: https://pacific-explorer.testnet.manta.network
 * Default RPC URL: https://manta-testnet.calderachain.xyz/http
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { mantaTestnet } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: mantaTestnet,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const mantaTestnet = createCommon({
	...nativeDefineChain({
		id: 3441005,
		name: 'Manta Pacific Testnet',
		nativeCurrency: {
			decimals: 18,
			name: 'ETH',
			symbol: 'ETH',
		},
		rpcUrls: {
			default: {
				http: ['https://manta-testnet.calderachain.xyz/http'],
			},
		},
		blockExplorers: {
			default: {
				name: 'Manta Testnet Explorer',
				url: 'https://pacific-explorer.testnet.manta.network',
				apiUrl: 'https://pacific-explorer.testnet.manta.network/api',
			},
		},
		contracts: {
			multicall3: {
				address: '0x211B1643b95Fe76f11eD8880EE810ABD9A4cf56C',
				blockCreated: 419915,
			},
		},
		testnet: true,
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
