// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { merlin as _merlin } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Merlin (chain ID 4200). Explorer: https://scan.merlinchain.io. Default RPC: https://rpc.merlinchain.io.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const merlin = createCommon({
	..._merlin,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
