// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { metachain as _metachain } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for MetaChain Mainnet (chain ID 571). Explorer: https://explorer.metatime.com. Default RPC: https://rpc.metatime.com.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const metachain = createCommon({
	..._metachain,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
