// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { nativeDefineChain } from '@tevm/utils'
import { createCommon } from '../createCommon.js'

/**
 * Creates a common configuration for the metalL2 chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 1750
 * Chain Name: Metal L2
 * Default Block Explorer: https://explorer.metall2.com
 * Default RPC URL: https://rpc.metall2.com
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { metalL2 } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: metalL2,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const metalL2 = createCommon({
	...nativeDefineChain({
		id: 1750,
		name: 'Metal L2',
		nativeCurrency: {
			name: 'Ether',
			symbol: 'ETH',
			decimals: 18,
		},
		rpcUrls: {
			default: {
				http: ['https://rpc.metall2.com'],
				webSocket: ['wss://rpc.metall2.com'],
			},
		},
		blockExplorers: {
			default: {
				name: 'Explorer',
				url: 'https://explorer.metall2.com',
				apiUrl: 'https://explorer.metall2.com/api',
			},
		},
		contracts: {
			multicall3: {
				address: '0xcA11bde05977b3631167028862bE2a173976CA11',
			},
		},
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
