// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { meterTestnet as _meterTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Meter Testnet (chain ID 83). Explorer: https://scan-warringstakes.meter.io. Default RPC: https://rpctest.meter.io.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const meterTestnet = createCommon({
	..._meterTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
