// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { meter as _meter } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Meter (chain ID 82). Explorer: https://scan.meter.io. Default RPC: https://rpc.meter.io.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const meter = createCommon({
	..._meter,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
