// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { metis as _metis } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Metis (chain ID 1088). Explorer: https://explorer.metis.io. Default RPC: https://metis.rpc.hypersync.xyz.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const metis = createCommon({
	..._metis,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
