// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { metisGoerli as _metisGoerli } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Metis Goerli (chain ID 599). Explorer: https://goerli.explorer.metisdevops.link. Default RPC: https://goerli.gateway.metisdevops.link.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const metisGoerli = createCommon({
	..._metisGoerli,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
