// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { nativeDefineChain } from '@tevm/utils'
import { createCommon } from '../createCommon.js'

/**
 * Creates a common configuration for the metisGoerli chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 599
 * Chain Name: Metis Goerli
 * Default Block Explorer: https://goerli.explorer.metisdevops.link
 * Default RPC URL: https://goerli.gateway.metisdevops.link
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { metisGoerli } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: metisGoerli,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const metisGoerli = createCommon({
	...nativeDefineChain({
		id: 599,
		name: 'Metis Goerli',
		nativeCurrency: {
			decimals: 18,
			name: 'Metis Goerli',
			symbol: 'METIS',
		},
		rpcUrls: {
			default: {
				http: ['https://goerli.gateway.metisdevops.link'],
			},
		},
		blockExplorers: {
			default: {
				name: 'Metis Goerli Explorer',
				url: 'https://goerli.explorer.metisdevops.link',
				apiUrl: 'https://goerli.explorer.metisdevops.link/api',
			},
		},
		contracts: {
			multicall3: {
				address: '0xca11bde05977b3631167028862be2a173976ca11',
				blockCreated: 1006207,
			},
		},
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
