// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { mev as _mev } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for MEVerse Chain Mainnet (chain ID 7518). Explorer: https://www.meversescan.io. Default RPC: https://rpc.meversemainnet.io.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const mev = createCommon({
	..._mev,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
