// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { mevTestnet as _mevTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for MEVerse Chain Testnet (chain ID 4759). Explorer: https://testnet.meversescan.io/. Default RPC: https://rpc.meversetestnet.io.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const mevTestnet = createCommon({
	..._mevTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
