// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { mintSepoliaTestnet as _mintSepoliaTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Mint Sepolia Testnet (chain ID 1686). Explorer: https://testnet-explorer.mintchain.io. Default RPC: https://testnet-rpc.mintchain.io.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const mintSepoliaTestnet = createCommon({
	..._mintSepoliaTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
