// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { modeTestnet as _modeTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Mode Testnet (chain ID 919). Explorer: https://sepolia.explorer.mode.network. Default RPC: https://sepolia.mode.network.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const modeTestnet = createCommon({
	..._modeTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
