// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { createCommon } from '../createCommon.js'
import { nativeDefineChain } from '@tevm/utils'

/**
 * Creates a common configuration for the modeTestnet chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 919
 * Chain Name: Mode Testnet
 * Default Block Explorer: https://sepolia.explorer.mode.network
 * Default RPC URL: https://sepolia.mode.network
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { modeTestnet } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: modeTestnet,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const modeTestnet = createCommon({
	...nativeDefineChain({
		id: 919,
		name: 'Mode Testnet',
		nativeCurrency: {
			name: 'Ether',
			symbol: 'ETH',
			decimals: 18,
		},
		rpcUrls: {
			default: {
				http: ['https://sepolia.mode.network'],
			},
		},
		blockExplorers: {
			default: {
				name: 'Blockscout',
				url: 'https://sepolia.explorer.mode.network',
				apiUrl: 'https://sepolia.explorer.mode.network/api',
			},
		},
		contracts: {
			gasPriceOracle: {
				address: '0x420000000000000000000000000000000000000F',
			},
			l1Block: {
				address: '0x4200000000000000000000000000000000000015',
			},
			l2CrossDomainMessenger: {
				address: '0x4200000000000000000000000000000000000007',
			},
			l2Erc721Bridge: {
				address: '0x4200000000000000000000000000000000000014',
			},
			l2StandardBridge: {
				address: '0x4200000000000000000000000000000000000010',
			},
			l2ToL1MessagePasser: {
				address: '0x4200000000000000000000000000000000000016',
			},
			l2OutputOracle: {
				11155111: {
					address: '0x2634BD65ba27AB63811c74A63118ACb312701Bfa',
					blockCreated: 3778393,
				},
			},
			portal: {
				11155111: {
					address: '0x320e1580effF37E008F1C92700d1eBa47c1B23fD',
					blockCreated: 3778395,
				},
			},
			l1StandardBridge: {
				11155111: {
					address: '0xbC5C679879B2965296756CD959C3C739769995E2',
					blockCreated: 3778392,
				},
			},
			multicall3: {
				address: '0xBAba8373113Fb7a68f195deF18732e01aF8eDfCF',
				blockCreated: 3019007,
			},
		},
		testnet: true,
		sourceId: 11155111,
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
