// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { moonriver as _moonriver } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Moonriver (chain ID 1285). Explorer: https://moonriver.moonscan.io. Default RPC: https://rpc.api.moonriver.moonbeam.network.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const moonriver = createCommon({
	..._moonriver,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
