// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { moonbeam as _moonbeam } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Moonbeam (chain ID 1284). Explorer: https://moonscan.io. Default RPC: https://rpc.api.moonbeam.network.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const moonbeam = createCommon({
	..._moonbeam,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
