// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { moonbeamDev as _moonbeamDev } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Moonbeam Development Node (chain ID 1281). Explorer: —. Default RPC: http://127.0.0.1:9944.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const moonbeamDev = createCommon({
	..._moonbeamDev,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
