// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { moonbaseAlpha as _moonbaseAlpha } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Moonbase Alpha (chain ID 1287). Explorer: https://moonbase.moonscan.io. Default RPC: https://rpc.api.moonbase.moonbeam.network.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const moonbaseAlpha = createCommon({
	..._moonbaseAlpha,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
