// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { createCommon } from '../createCommon.js'
import { nativeDefineChain } from '@tevm/utils'

/**
 * Creates a common configuration for the moonriver chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 1285
 * Chain Name: Moonriver
 * Default Block Explorer: https://moonriver.moonscan.io
 * Default RPC URL: https://moonriver.public.blastapi.io
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { moonriver } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: moonriver,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const moonriver = createCommon({
	...nativeDefineChain({
		id: 1285,
		name: 'Moonriver',
		nativeCurrency: {
			name: 'MOVR',
			symbol: 'MOVR',
			decimals: 18,
		},
		rpcUrls: {
			default: {
				http: ['https://moonriver.public.blastapi.io'],
				webSocket: ['wss://moonriver.public.blastapi.io'],
			},
		},
		blockExplorers: {
			default: {
				name: 'Moonscan',
				url: 'https://moonriver.moonscan.io',
				apiUrl: 'https://api-moonriver.moonscan.io/api',
			},
		},
		contracts: {
			multicall3: {
				address: '0xcA11bde05977b3631167028862bE2a173976CA11',
				blockCreated: 1597904,
			},
		},
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
