// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { morphSepolia as _morphSepolia } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Morph Sepolia (chain ID 2710). Explorer: https://explorer-testnet.morphl2.io. Default RPC: https://rpc-testnet.morphl2.io.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const morphSepolia = createCommon({
	..._morphSepolia,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
