// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { createCommon } from '../createCommon.js'
import { nativeDefineChain } from '@tevm/utils'

/**
 * Creates a common configuration for the neonMainnet chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 245022934
 * Chain Name: Neon EVM MainNet
 * Default Block Explorer: https://neonscan.org
 * Default RPC URL: https://neon-proxy-mainnet.solana.p2p.org
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { neonMainnet } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: neonMainnet,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const neonMainnet = createCommon({
	...nativeDefineChain({
		id: 245022934,
		name: 'Neon EVM MainNet',
		nativeCurrency: {
			name: 'NEON',
			symbol: 'NEON',
			decimals: 18,
		},
		rpcUrls: {
			default: {
				http: ['https://neon-proxy-mainnet.solana.p2p.org'],
			},
		},
		blockExplorers: {
			default: {
				name: 'Neonscan',
				url: 'https://neonscan.org',
			},
		},
		contracts: {
			multicall3: {
				address: '0xca11bde05977b3631167028862be2a173976ca11',
				blockCreated: 206545524,
			},
		},
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
