// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { createCommon } from '../createCommon.js'
import { nativeDefineChain } from '@tevm/utils'

/**
 * Creates a common configuration for the neonDevnet chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 245022926
 * Chain Name: Neon EVM DevNet
 * Default Block Explorer: https://devnet.neonscan.org
 * Default RPC URL: https://devnet.neonevm.org
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { neonDevnet } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: neonDevnet,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const neonDevnet = createCommon({
	...nativeDefineChain({
		id: 245022926,
		name: 'Neon EVM DevNet',
		nativeCurrency: {
			name: 'NEON',
			symbol: 'NEON',
			decimals: 18,
		},
		rpcUrls: {
			default: {
				http: ['https://devnet.neonevm.org'],
			},
		},
		blockExplorers: {
			default: {
				name: 'Neonscan',
				url: 'https://devnet.neonscan.org',
			},
		},
		contracts: {
			multicall3: {
				address: '0xca11bde05977b3631167028862be2a173976ca11',
				blockCreated: 205206112,
			},
		},
		testnet: true,
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
