// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { neonMainnet as _neonMainnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Neon EVM MainNet (chain ID 245022934). Explorer: https://neonscan.org. Default RPC: https://neon-proxy-mainnet.solana.p2p.org.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const neonMainnet = createCommon({
	..._neonMainnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
