// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { nexilix as _nexilix } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Nexilix Smart Chain (chain ID 240). Explorer: https://scan.nexilix.com. Default RPC: https://rpcurl.pos.nexilix.com.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const nexilix = createCommon({
	..._nexilix,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
