// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { createCommon } from '../createCommon.js'
import { nativeDefineChain } from '@tevm/utils'

/**
 * Creates a common configuration for the nexi chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 4242
 * Chain Name: Nexi
 * Default Block Explorer: https://www.nexiscan.com
 * Default RPC URL: https://rpc.chain.nexi.technology
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { nexi } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: nexi,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const nexi = createCommon({
	...nativeDefineChain({
		id: 4242,
		name: 'Nexi',
		nativeCurrency: {
			name: 'Nexi',
			symbol: 'NEXI',
			decimals: 18,
		},
		rpcUrls: {
			default: {
				http: ['https://rpc.chain.nexi.technology'],
			},
		},
		blockExplorers: {
			default: {
				name: 'NexiScan',
				url: 'https://www.nexiscan.com',
				apiUrl: 'https://www.nexiscan.com/api',
			},
		},
		contracts: {
			multicall3: {
				address: '0x0277A46Cc69A57eE3A6C8c158bA874832F718B8E',
				blockCreated: 25770160,
			},
		},
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
