// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { oortMainnetDev as _oortMainnetDev } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for OORT MainnetDev (chain ID 9700). Explorer: https://dev-scan.oortech.com. Default RPC: https://dev-rpc.oortech.com.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const oortMainnetDev = createCommon({
	..._oortMainnetDev,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
