// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { nativeDefineChain } from '@tevm/utils'
import { createCommon } from '../createCommon.js'

/**
 * Creates a common configuration for the opBNBTestnet chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 5611
 * Chain Name: opBNB Testnet
 * Default Block Explorer: https://testnet.opbnbscan.com
 * Default RPC URL: https://opbnb-testnet-rpc.bnbchain.org
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { opBNBTestnet } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: opBNBTestnet,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const opBNBTestnet = createCommon({
	...nativeDefineChain({
		id: 5611,
		name: 'opBNB Testnet',
		nativeCurrency: {
			decimals: 18,
			name: 'tBNB',
			symbol: 'tBNB',
		},
		rpcUrls: {
			default: {
				http: ['https://opbnb-testnet-rpc.bnbchain.org'],
			},
		},
		blockExplorers: {
			default: {
				name: 'opbnbscan',
				url: 'https://testnet.opbnbscan.com',
			},
		},
		contracts: {
			gasPriceOracle: {
				address: '0x420000000000000000000000000000000000000F',
			},
			l1Block: {
				address: '0x4200000000000000000000000000000000000015',
			},
			l2CrossDomainMessenger: {
				address: '0x4200000000000000000000000000000000000007',
			},
			l2Erc721Bridge: {
				address: '0x4200000000000000000000000000000000000014',
			},
			l2StandardBridge: {
				address: '0x4200000000000000000000000000000000000010',
			},
			l2ToL1MessagePasser: {
				address: '0x4200000000000000000000000000000000000016',
			},
			multicall3: {
				address: '0xcA11bde05977b3631167028862bE2a173976CA11',
				blockCreated: 3705108,
			},
			l2OutputOracle: {
				97: {
					address: '0xFf2394Bb843012562f4349C6632a0EcB92fC8810',
				},
			},
			portal: {
				97: {
					address: '0x4386C8ABf2009aC0c263462Da568DD9d46e52a31',
				},
			},
			l1StandardBridge: {
				97: {
					address: '0x677311Fd2cCc511Bbc0f581E8d9a07B033D5E840',
				},
			},
		},
		testnet: true,
		sourceId: 97,
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
