// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { nativeDefineChain } from '@tevm/utils'
import { createCommon } from '../createCommon.js'

/**
 * Creates a common configuration for the opBNB chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 204
 * Chain Name: opBNB
 * Default Block Explorer: https://mainnet.opbnbscan.com
 * Default RPC URL: https://opbnb-mainnet-rpc.bnbchain.org
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { opBNB } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: opBNB,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const opBNB = createCommon({
	...nativeDefineChain({
		id: 204,
		name: 'opBNB',
		nativeCurrency: {
			name: 'BNB',
			symbol: 'BNB',
			decimals: 18,
		},
		rpcUrls: {
			default: {
				http: ['https://opbnb-mainnet-rpc.bnbchain.org'],
			},
		},
		blockExplorers: {
			default: {
				name: 'opBNB (BSCScan)',
				url: 'https://opbnb.bscscan.com',
				apiUrl: 'https://api-opbnb.bscscan.com/api',
			},
		},
		contracts: {
			gasPriceOracle: {
				address: '0x420000000000000000000000000000000000000F',
			},
			l1Block: {
				address: '0x4200000000000000000000000000000000000015',
			},
			l2CrossDomainMessenger: {
				address: '0x4200000000000000000000000000000000000007',
			},
			l2Erc721Bridge: {
				address: '0x4200000000000000000000000000000000000014',
			},
			l2StandardBridge: {
				address: '0x4200000000000000000000000000000000000010',
			},
			l2ToL1MessagePasser: {
				address: '0x4200000000000000000000000000000000000016',
			},
			multicall3: {
				address: '0xcA11bde05977b3631167028862bE2a173976CA11',
				blockCreated: 512881,
			},
			l2OutputOracle: {
				56: {
					address: '0x153CAB79f4767E2ff862C94aa49573294B13D169',
				},
			},
			portal: {
				56: {
					address: '0x1876EA7702C0ad0C6A2ae6036DE7733edfBca519',
				},
			},
			l1StandardBridge: {
				56: {
					address: '0xF05F0e4362859c3331Cb9395CBC201E3Fa6757Ea',
				},
			},
		},
		sourceId: 56,
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
