// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { opBNBTestnet as _opBNBTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for opBNB Testnet (chain ID 5611). Explorer: https://testnet.opbnbscan.com. Default RPC: https://opbnb-testnet-rpc.bnbchain.org.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const opBNBTestnet = createCommon({
	..._opBNBTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
