// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { nativeDefineChain } from '@tevm/utils'
import { createCommon } from '../createCommon.js'

/**
 * Creates a common configuration for the optimismGoerli chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 420
 * Chain Name: Optimism Goerli
 * Default Block Explorer: https://goerli-optimism.etherscan.io
 * Default RPC URL: https://goerli.optimism.io
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { optimismGoerli } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: optimismGoerli,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const optimismGoerli = createCommon({
	...nativeDefineChain({
		id: 420,
		name: 'Optimism Goerli',
		nativeCurrency: {
			name: 'Goerli Ether',
			symbol: 'ETH',
			decimals: 18,
		},
		rpcUrls: {
			default: {
				http: ['https://goerli.optimism.io'],
			},
		},
		blockExplorers: {
			default: {
				name: 'Etherscan',
				url: 'https://goerli-optimism.etherscan.io',
				apiUrl: 'https://goerli-optimism.etherscan.io/api',
			},
		},
		contracts: {
			gasPriceOracle: {
				address: '0x420000000000000000000000000000000000000F',
			},
			l1Block: {
				address: '0x4200000000000000000000000000000000000015',
			},
			l2CrossDomainMessenger: {
				address: '0x4200000000000000000000000000000000000007',
			},
			l2Erc721Bridge: {
				address: '0x4200000000000000000000000000000000000014',
			},
			l2StandardBridge: {
				address: '0x4200000000000000000000000000000000000010',
			},
			l2ToL1MessagePasser: {
				address: '0x4200000000000000000000000000000000000016',
			},
			l2OutputOracle: {
				5: {
					address: '0xE6Dfba0953616Bacab0c9A8ecb3a9BBa77FC15c0',
				},
			},
			multicall3: {
				address: '0xca11bde05977b3631167028862be2a173976ca11',
				blockCreated: 49461,
			},
			portal: {
				5: {
					address: '0x5b47E1A08Ea6d985D6649300584e6722Ec4B1383',
				},
			},
			l1StandardBridge: {
				5: {
					address: '0x636Af16bf2f682dD3109e60102b8E1A089FedAa8',
				},
			},
		},
		testnet: true,
		sourceId: 5,
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
