// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { optimism as _optimism } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for OP Mainnet (chain ID 10). Explorer: https://optimistic.etherscan.io. Default RPC: https://mainnet.optimism.io.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const optimism = createCommon({
	..._optimism,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
