// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { otimDevnet as _otimDevnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Otim Devnet (chain ID 41144114). Explorer: —. Default RPC: http://devnet.otim.xyz.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const otimDevnet = createCommon({
	..._otimDevnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
