// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { createCommon } from '../createCommon.js'
import { nativeDefineChain } from '@tevm/utils'

/**
 * Creates a common configuration for the palm chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 11297108109
 * Chain Name: Palm
 * Default Block Explorer: https://palm.chainlens.com
 * Default RPC URL: https://palm-mainnet.public.blastapi.io
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { palm } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: palm,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const palm = createCommon({
	...nativeDefineChain({
		id: 11297108109,
		name: 'Palm',
		nativeCurrency: {
			decimals: 18,
			name: 'PALM',
			symbol: 'PALM',
		},
		rpcUrls: {
			default: {
				http: ['https://palm-mainnet.public.blastapi.io'],
				webSocket: ['wss://palm-mainnet.public.blastapi.io'],
			},
		},
		blockExplorers: {
			default: {
				name: 'Chainlens',
				url: 'https://palm.chainlens.com',
			},
		},
		contracts: {
			multicall3: {
				address: '0xca11bde05977b3631167028862be2a173976ca11',
				blockCreated: 15429248,
			},
		},
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
