// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { palmTestnet as _palmTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Palm Testnet (chain ID 11297108099). Explorer: https://palm.chainlens.com. Default RPC: https://palm-mainnet.public.blastapi.io.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const palmTestnet = createCommon({
	..._palmTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
