// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { createCommon } from '../createCommon.js'
import { nativeDefineChain } from '@tevm/utils'

/**
 * Creates a common configuration for the pgn chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 424
 * Chain Name: PGN
 * Default Block Explorer: https://explorer.publicgoods.network
 * Default RPC URL: https://rpc.publicgoods.network
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { pgn } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: pgn,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const pgn = createCommon({
	...nativeDefineChain({
		id: 424,
		name: 'PGN',
		nativeCurrency: {
			name: 'Ether',
			symbol: 'ETH',
			decimals: 18,
		},
		rpcUrls: {
			default: {
				http: ['https://rpc.publicgoods.network'],
			},
		},
		blockExplorers: {
			default: {
				name: 'PGN Explorer',
				url: 'https://explorer.publicgoods.network',
				apiUrl: 'https://explorer.publicgoods.network/api',
			},
		},
		contracts: {
			l2OutputOracle: {
				'1': {
					address: '0x9E6204F750cD866b299594e2aC9eA824E2e5f95c',
				},
			},
			multicall3: {
				address: '0xcA11bde05977b3631167028862bE2a173976CA11',
				blockCreated: 3380209,
			},
			portal: {
				'1': {
					address: '0xb26Fd985c5959bBB382BAFdD0b879E149e48116c',
				},
			},
			l1StandardBridge: {
				'1': {
					address: '0xD0204B9527C1bA7bD765Fa5CCD9355d38338272b',
				},
			},
		},
		sourceId: 1,
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
