// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { pgn as _pgn } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for PGN (chain ID 424). Explorer: https://explorer.publicgoods.network. Default RPC: https://rpc.publicgoods.network.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const pgn = createCommon({
	..._pgn,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
