// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { createCommon } from '../createCommon.js'
import { nativeDefineChain } from '@tevm/utils'

/**
 * Creates a common configuration for the pgnTestnet chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 58008
 * Chain Name: PGN
 * Default Block Explorer: https://explorer.sepolia.publicgoods.network
 * Default RPC URL: https://sepolia.publicgoods.network
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { pgnTestnet } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: pgnTestnet,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const pgnTestnet = createCommon({
	...nativeDefineChain({
		id: 58008,
		name: 'PGN ',
		nativeCurrency: {
			name: 'Ether',
			symbol: 'ETH',
			decimals: 18,
		},
		rpcUrls: {
			default: {
				http: ['https://sepolia.publicgoods.network'],
			},
		},
		blockExplorers: {
			default: {
				name: 'PGN Testnet Explorer',
				url: 'https://explorer.sepolia.publicgoods.network',
				apiUrl: 'https://explorer.sepolia.publicgoods.network/api',
			},
		},
		contracts: {
			l2OutputOracle: {
				'11155111': {
					address: '0xD5bAc3152ffC25318F848B3DD5dA6C85171BaEEe',
				},
			},
			portal: {
				'11155111': {
					address: '0xF04BdD5353Bb0EFF6CA60CfcC78594278eBfE179',
				},
			},
			l1StandardBridge: {
				'11155111': {
					address: '0xFaE6abCAF30D23e233AC7faF747F2fC3a5a6Bfa3',
				},
			},
			multicall3: {
				address: '0xcA11bde05977b3631167028862bE2a173976CA11',
				blockCreated: 3754925,
			},
		},
		sourceId: 11155111,
		testnet: true,
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
