// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { createCommon } from '../createCommon.js'
import { nativeDefineChain } from '@tevm/utils'

/**
 * Creates a common configuration for the phoenix chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 13381
 * Chain Name: Phoenix Blockchain
 * Default Block Explorer: https://phoenixplorer.com
 * Default RPC URL: https://rpc.phoenixplorer.com
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { phoenix } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: phoenix,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const phoenix = createCommon({
	...nativeDefineChain({
		id: 13381,
		name: 'Phoenix Blockchain',
		nativeCurrency: {
			name: 'Phoenix',
			symbol: 'PHX',
			decimals: 18,
		},
		rpcUrls: {
			default: {
				http: ['https://rpc.phoenixplorer.com'],
			},
		},
		blockExplorers: {
			default: {
				name: 'Phoenixplorer',
				url: 'https://phoenixplorer.com',
				apiUrl: 'https://phoenixplorer.com/api',
			},
		},
		contracts: {
			multicall3: {
				address: '0x498cF757a575cFF2c2Ed9f532f56Efa797f86442',
				blockCreated: 5620192,
			},
		},
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
