// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { phoenix as _phoenix } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Phoenix Blockchain (chain ID 13381). Explorer: https://phoenixplorer.com. Default RPC: https://rpc.phoenixplorer.com.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const phoenix = createCommon({
	..._phoenix,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
