// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { plinga as _plinga } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Plinga (chain ID 242). Explorer: https://www.plgscan.com. Default RPC: https://rpcurl.mainnet.plgchain.com.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const plinga = createCommon({
	..._plinga,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
