// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { plumeTestnet as _plumeTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Plume Testnet (Legacy) (chain ID 161221135). Explorer: https://testnet-explorer.plumenetwork.xyz. Default RPC: https://testnet-rpc.plumenetwork.xyz/http.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const plumeTestnet = createCommon({
	..._plumeTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
