// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { nativeDefineChain } from '@tevm/utils'
import { createCommon } from '../createCommon.js'

const _polygon = nativeDefineChain({
	id: 137,
	name: 'Polygon',
	nativeCurrency: {
		name: 'POL',
		symbol: 'POL',
		decimals: 18,
	},
	rpcUrls: {
		default: {
			http: ['https://polygon-rpc.com'],
		},
	},
	blockExplorers: {
		default: {
			name: 'PolygonScan',
			url: 'https://polygonscan.com',
			apiUrl: 'https://api.polygonscan.com/api',
		},
	},
	contracts: {
		multicall3: {
			address: '0xca11bde05977b3631167028862be2a173976ca11',
			blockCreated: 25770160,
		},
	},
})

/**
 * Creates a common configuration for the polygon chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 137
 * Chain Name: Polygon
 * Default Block Explorer: https://polygonscan.com
 * Default RPC URL: https://polygon-rpc.com
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { polygon } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: polygon,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const polygon = createCommon({
	..._polygon,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
