// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { createCommon } from '../createCommon.js'
import { nativeDefineChain } from '@tevm/utils'

/**
 * Creates a common configuration for the polygonZkEvmTestnet chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 1442
 * Chain Name: Polygon zkEVM Testnet
 * Default Block Explorer: https://testnet-zkevm.polygonscan.com
 * Default RPC URL: https://rpc.public.zkevm-test.net
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { polygonZkEvmTestnet } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: polygonZkEvmTestnet,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const polygonZkEvmTestnet = createCommon({
	...nativeDefineChain({
		id: 1442,
		name: 'Polygon zkEVM Testnet',
		nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
		rpcUrls: {
			default: {
				http: ['https://rpc.public.zkevm-test.net'],
			},
		},
		blockExplorers: {
			blockscout: {
				name: 'Blockscout',
				url: 'https://explorer.public.zkevm-test.net',
			},
			default: {
				name: 'PolygonScan',
				url: 'https://testnet-zkevm.polygonscan.com',
			},
		},
		testnet: true,
		contracts: {
			multicall3: {
				address: '0xca11bde05977b3631167028862be2a173976ca11',
				blockCreated: 525686,
			},
		},
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
