// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { polygon as _polygon } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Polygon (chain ID 137). Explorer: https://polygonscan.com. Default RPC: https://polygon.drpc.org.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const polygon = createCommon({
	..._polygon,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
