// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { polygonAmoy as _polygonAmoy } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Polygon Amoy (chain ID 80002). Explorer: https://amoy.polygonscan.com. Default RPC: https://rpc-amoy.polygon.technology.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const polygonAmoy = createCommon({
	..._polygonAmoy,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
