// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { nativeDefineChain } from '@tevm/utils'
import { createCommon } from '../createCommon.js'

/**
 * Creates a common configuration for the polygonAmoy chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 80002
 * Chain Name: Polygon Amoy
 * Default Block Explorer: https://amoy.polygonscan.com
 * Default RPC URL: https://rpc-amoy.polygon.technology
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { polygonAmoy } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: polygonAmoy,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const polygonAmoy = createCommon({
	...nativeDefineChain({
		id: 80002,
		name: 'Polygon Amoy',
		nativeCurrency: {
			name: 'POL',
			symbol: 'POL',
			decimals: 18,
		},
		rpcUrls: {
			default: {
				http: ['https://rpc-amoy.polygon.technology'],
			},
		},
		blockExplorers: {
			default: {
				name: 'PolygonScan',
				url: 'https://amoy.polygonscan.com',
				apiUrl: 'https://api-amoy.polygonscan.com/api',
			},
		},
		contracts: {
			multicall3: {
				address: '0xca11bde05977b3631167028862be2a173976ca11',
				blockCreated: 3127388,
			},
		},
		testnet: true,
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
