// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { pulsechain as _pulsechain } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for PulseChain (chain ID 369). Explorer: https://ipfs.scan.pulsechain.com. Default RPC: https://rpc.pulsechain.com.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const pulsechain = createCommon({
	..._pulsechain,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
