// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { createCommon } from '../createCommon.js'
import { nativeDefineChain } from '@tevm/utils'

/**
 * Creates a common configuration for the pulsechainV4 chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 943
 * Chain Name: PulseChain V4
 * Default Block Explorer: https://scan.v4.testnet.pulsechain.com
 * Default RPC URL: https://rpc.v4.testnet.pulsechain.com
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { pulsechainV4 } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: pulsechainV4,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const pulsechainV4 = createCommon({
	...nativeDefineChain({
		id: 943,
		name: 'PulseChain V4',
		nativeCurrency: { name: 'V4 Pulse', symbol: 'v4PLS', decimals: 18 },
		rpcUrls: {
			default: {
				http: ['https://rpc.v4.testnet.pulsechain.com'],
				webSocket: ['wss://ws.v4.testnet.pulsechain.com'],
			},
		},
		blockExplorers: {
			default: {
				name: 'PulseScan',
				url: 'https://scan.v4.testnet.pulsechain.com',
			},
		},
		testnet: true,
		contracts: {
			ensRegistry: {
				address: '0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e',
			},
			multicall3: {
				address: '0xca11bde05977b3631167028862be2a173976ca11',
				blockCreated: 14353601,
			},
		},
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
