// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { createCommon } from '../createCommon.js'
import { nativeDefineChain } from '@tevm/utils'

/**
 * Creates a common configuration for the qMainnet chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 35441
 * Chain Name: Q Mainnet
 * Default Block Explorer: https://explorer.q.org
 * Default RPC URL: https://rpc.q.org
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { qMainnet } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: qMainnet,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const qMainnet = createCommon({
	...nativeDefineChain({
		id: 35441,
		name: 'Q Mainnet',
		nativeCurrency: { name: 'Q', symbol: 'Q', decimals: 18 },
		rpcUrls: {
			default: {
				http: ['https://rpc.q.org'],
			},
		},
		blockExplorers: {
			default: {
				name: 'Q Mainnet Explorer',
				url: 'https://explorer.q.org',
				apiUrl: 'https://explorer.q.org/api',
			},
		},
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
