// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { qTestnet as _qTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Q Testnet (chain ID 35443). Explorer: https://explorer.qtestnet.org. Default RPC: https://rpc.qtestnet.org.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const qTestnet = createCommon({
	..._qTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
