// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { real as _real } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for re.al (chain ID 111188). Explorer: https://explorer.re.al. Default RPC: https://rpc.realforreal.gelato.digital.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const real = createCommon({
	..._real,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
