// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { createCommon } from '../createCommon.js'
import { nativeDefineChain } from '@tevm/utils'

/**
 * Creates a common configuration for the real chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 111188
 * Chain Name: re.al
 * Default Block Explorer: https://explorer.re.al
 * Default RPC URL: https://rpc.realforreal.gelato.digital
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { real } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: real,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const real = createCommon({
	...nativeDefineChain({
		id: 111188,
		name: 're.al',
		nativeCurrency: { name: 'reETH', symbol: 'reETH', decimals: 18 },
		rpcUrls: {
			default: {
				http: ['https://rpc.realforreal.gelato.digital'],
			},
		},
		blockExplorers: {
			default: {
				name: 're.al Explorer',
				url: 'https://explorer.re.al',
				apiUrl: 'https://explorer.re.al/api/v2',
			},
		},
		contracts: {
			multicall3: {
				address: '0xcA11bde05977b3631167028862bE2a173976CA11',
				blockCreated: 695,
			},
		},
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
