// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { redbellyTestnet as _redbellyTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Redbelly Network Testnet (chain ID 153). Explorer: https://redbelly.testnet.routescan.io. Default RPC: https://governors.testnet.redbelly.network.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const redbellyTestnet = createCommon({
	..._redbellyTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
