// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { createCommon } from '../createCommon.js'
import { nativeDefineChain } from '@tevm/utils'

/**
 * Creates a common configuration for the redstone chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 690
 * Chain Name: Redstone
 * Default Block Explorer: https://explorer.redstone.xyz
 * Default RPC URL: https://rpc.redstonechain.com
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { redstone } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: redstone,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const redstone = createCommon({
	...nativeDefineChain({
		id: 690,
		name: 'Redstone',
		nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
		rpcUrls: {
			default: {
				http: ['https://rpc.redstonechain.com'],
				webSocket: ['wss://rpc.redstonechain.com'],
			},
		},
		blockExplorers: {
			default: {
				name: 'Blockscout',
				url: 'https://explorer.redstone.xyz',
			},
		},
		contracts: {
			gasPriceOracle: { address: '0x420000000000000000000000000000000000000F' },
			l1Block: { address: '0x4200000000000000000000000000000000000015' },
			l2CrossDomainMessenger: { address: '0x4200000000000000000000000000000000000007' },
			l2Erc721Bridge: { address: '0x4200000000000000000000000000000000000014' },
			l2StandardBridge: { address: '0x4200000000000000000000000000000000000010' },
			l2ToL1MessagePasser: { address: '0x4200000000000000000000000000000000000016' },
			multicall3: { address: '0xca11bde05977b3631167028862be2a173976ca11' },
		},
		sourceId: 1,
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
