// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { nativeDefineChain } from '@tevm/utils'
import { createCommon } from '../createCommon.js'

/**
 * Creates a common configuration for the reyaNetwork chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 1729
 * Chain Name: Reya Network
 * Default Block Explorer: https://explorer.reya.network
 * Default RPC URL: https://rpc.reya.network
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { reyaNetwork } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: reyaNetwork,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const reyaNetwork = createCommon({
	...nativeDefineChain({
		id: 1729,
		name: 'Reya Network',
		nativeCurrency: {
			decimals: 18,
			name: 'Ether',
			symbol: 'ETH',
		},
		rpcUrls: {
			default: {
				http: ['https://rpc.reya.network'],
				webSocket: ['wss://ws.reya.network'],
			},
		},
		blockExplorers: {
			default: {
				name: 'Reya Network Explorer',
				url: 'https://explorer.reya.network',
			},
		},
		testnet: false,
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
