// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { nativeDefineChain } from '@tevm/utils'
import { createCommon } from '../createCommon.js'

/**
 * Creates a common configuration for the rolluxTestnet chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 57000
 * Chain Name: Rollux Testnet
 * Default Block Explorer: https://rollux.tanenbaum.io
 * Default RPC URL: https://rpc-tanenbaum.rollux.com/
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { rolluxTestnet } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: rolluxTestnet,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const rolluxTestnet = createCommon({
	...nativeDefineChain({
		id: 57000,
		name: 'Rollux Testnet',
		nativeCurrency: {
			decimals: 18,
			name: 'Syscoin',
			symbol: 'SYS',
		},
		rpcUrls: {
			default: {
				http: ['https://rpc-tanenbaum.rollux.com/'],
				webSocket: ['wss://rpc-tanenbaum.rollux.com/wss'],
			},
		},
		blockExplorers: {
			default: {
				name: 'RolluxTestnetExplorer',
				url: 'https://rollux.tanenbaum.io',
				apiUrl: 'https://rollux.tanenbaum.io/api',
			},
		},
		contracts: {
			multicall3: {
				address: '0xcA11bde05977b3631167028862bE2a173976CA11',
				blockCreated: 1813675,
			},
		},
		testnet: true,
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
