// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { nativeDefineChain } from '@tevm/utils'
import { createCommon } from '../createCommon.js'

/**
 * Creates a common configuration for the rollux chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 570
 * Chain Name: Rollux Mainnet
 * Default Block Explorer: https://explorer.rollux.com
 * Default RPC URL: https://rpc.rollux.com
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { rollux } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: rollux,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const rollux = createCommon({
	...nativeDefineChain({
		id: 570,
		name: 'Rollux Mainnet',
		nativeCurrency: {
			decimals: 18,
			name: 'Syscoin',
			symbol: 'SYS',
		},
		rpcUrls: {
			default: {
				http: ['https://rpc.rollux.com'],
				webSocket: ['wss://rpc.rollux.com/wss'],
			},
		},
		blockExplorers: {
			default: {
				name: 'RolluxExplorer',
				url: 'https://explorer.rollux.com',
				apiUrl: 'https://explorer.rollux.com/api',
			},
		},
		contracts: {
			multicall3: {
				address: '0xcA11bde05977b3631167028862bE2a173976CA11',
				blockCreated: 119222,
			},
		},
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
