// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { rootstock as _rootstock } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Rootstock Mainnet (chain ID 30). Explorer: https://explorer.rsk.co. Default RPC: https://public-node.rsk.co.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const rootstock = createCommon({
	..._rootstock,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
