// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { createCommon } from '../createCommon.js'
import { nativeDefineChain } from '@tevm/utils'

/**
 * Creates a common configuration for the rootstock chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 30
 * Chain Name: Rootstock Mainnet
 * Default Block Explorer: https://explorer.rsk.co
 * Default RPC URL: https://public-node.rsk.co
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { rootstock } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: rootstock,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const rootstock = createCommon({
	...nativeDefineChain({
		id: 30,
		name: 'Rootstock Mainnet',
		nativeCurrency: {
			decimals: 18,
			name: 'Rootstock Bitcoin',
			symbol: 'RBTC',
		},
		rpcUrls: {
			default: {
				http: ['https://public-node.rsk.co'],
			},
		},
		blockExplorers: {
			default: {
				name: 'RSK Explorer',
				url: 'https://explorer.rsk.co',
			},
		},
		contracts: {
			multicall3: {
				address: '0xcA11bde05977b3631167028862bE2a173976CA11',
				blockCreated: 4249540,
			},
		},
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
