// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { createCommon } from '../createCommon.js'
import { nativeDefineChain } from '@tevm/utils'

/**
 * Creates a common configuration for the rootstockTestnet chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 31
 * Chain Name: Rootstock Testnet
 * Default Block Explorer: https://explorer.testnet.rootstock.io
 * Default RPC URL: https://public-node.testnet.rsk.co
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { rootstockTestnet } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: rootstockTestnet,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const rootstockTestnet = createCommon({
	...nativeDefineChain({
		id: 31,
		name: 'Rootstock Testnet',
		nativeCurrency: {
			decimals: 18,
			name: 'Rootstock Bitcoin',
			symbol: 'tRBTC',
		},
		rpcUrls: {
			default: {
				http: ['https://public-node.testnet.rsk.co'],
			},
		},
		blockExplorers: {
			default: {
				name: 'RSK Explorer',
				url: 'https://explorer.testnet.rootstock.io',
			},
		},
		contracts: {
			multicall3: {
				address: '0xcA11bde05977b3631167028862bE2a173976CA11',
				blockCreated: 2771150,
			},
		},
		testnet: true,
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
