// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { rootstockTestnet as _rootstockTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Rootstock Testnet (chain ID 31). Explorer: https://explorer.testnet.rootstock.io. Default RPC: https://public-node.testnet.rsk.co.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const rootstockTestnet = createCommon({
	..._rootstockTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
