// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { createCommon } from '../createCommon.js'
import { nativeDefineChain } from '@tevm/utils'

/**
 * Creates a common configuration for the rootPorcini chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 7672
 * Chain Name: The Root Network - Porcini
 * Default Block Explorer: https://porcini.rootscan.io
 * Default RPC URL: https://porcini.rootnet.app/archive
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { rootPorcini } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: rootPorcini,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const rootPorcini = createCommon({
	...nativeDefineChain({
		id: 7672,
		name: 'The Root Network - Porcini',
		nativeCurrency: {
			decimals: 18,
			name: 'XRP',
			symbol: 'XRP',
		},
		rpcUrls: {
			default: {
				http: ['https://porcini.rootnet.app/archive'],
				webSocket: ['wss://porcini.rootnet.app/archive/ws'],
			},
		},
		blockExplorers: {
			default: {
				name: 'Rootscan',
				url: 'https://porcini.rootscan.io',
			},
		},
		contracts: {
			multicall3: {
				address: '0xc9C2E2429AeC354916c476B30d729deDdC94988d',
				blockCreated: 10555692,
			},
		},
		testnet: true,
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
