// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { createCommon } from '../createCommon.js'
import { nativeDefineChain } from '@tevm/utils'

/**
 * Creates a common configuration for the rss3 chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 12553
 * Chain Name: RSS3 VSL Mainnet
 * Default Block Explorer: https://scan.rss3.io
 * Default RPC URL: https://rpc.rss3.io
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { rss3 } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: rss3,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const rss3 = createCommon({
	...nativeDefineChain({
		id: 12553,
		name: 'RSS3 VSL Mainnet',
		nativeCurrency: {
			name: 'RSS3',
			symbol: 'RSS3',
			decimals: 18,
		},
		rpcUrls: {
			default: {
				http: ['https://rpc.rss3.io'],
			},
		},
		blockExplorers: {
			default: {
				name: 'RSS3 VSL Mainnet Scan',
				url: 'https://scan.rss3.io',
				apiUrl: 'https://scan.rss3.io/api',
			},
		},
		contracts: {
			multicall3: {
				address: '0xca11bde05977b3631167028862be2a173976ca11',
				blockCreated: 14193,
			},
		},
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
