// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { rss3 as _rss3 } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for RSS3 VSL Mainnet (chain ID 12553). Explorer: https://scan.rss3.io. Default RPC: https://rpc.rss3.io.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const rss3 = createCommon({
	..._rss3,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
