// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { saigon as _saigon } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Ronin Saigon Testnet (chain ID 202601). Explorer: https://saigon-explorer.roninchain.com. Default RPC: https://saigon-testnet.roninchain.com/rpc.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const saigon = createCommon({
	..._saigon,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
