// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { sapphireTestnet as _sapphireTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Oasis Sapphire Testnet (chain ID 23295). Explorer: https://explorer.oasis.io/testnet/sapphire. Default RPC: https://testnet.sapphire.oasis.dev.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const sapphireTestnet = createCommon({
	..._sapphireTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
