// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { satoshiVM as _satoshiVM } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for SatoshiVM Alpha Mainnet (chain ID 3109). Explorer: https://svmscan.io. Default RPC: https://alpha-rpc-node-http.svmscan.io.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const satoshiVM = createCommon({
	..._satoshiVM,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
