// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { scroll as _scroll } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Scroll (chain ID 534352). Explorer: https://scrollscan.com. Default RPC: https://rpc.scroll.io.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const scroll = createCommon({
	..._scroll,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
