// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { scrollSepolia as _scrollSepolia } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Scroll Sepolia (chain ID 534351). Explorer: https://sepolia.scrollscan.com. Default RPC: https://sepolia-rpc.scroll.io.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const scrollSepolia = createCommon({
	..._scrollSepolia,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
