// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { seiTestnet as _seiTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Sei Testnet (chain ID 1328). Explorer: https://testnet.seiscan.io. Default RPC: https://evm-rpc-testnet.sei-apis.com.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const seiTestnet = createCommon({
	..._seiTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
