// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { shardeumSphinx as _shardeumSphinx } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Shardeum Sphinx (chain ID 8082). Explorer: https://explorer-sphinx.shardeum.org. Default RPC: https://sphinx.shardeum.org.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const shardeumSphinx = createCommon({
	..._shardeumSphinx,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
