// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { shimmerTestnet as _shimmerTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Shimmer Testnet (chain ID 1073). Explorer: https://explorer.evm.testnet.shimmer.network. Default RPC: https://json-rpc.evm.testnet.shimmer.network.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const shimmerTestnet = createCommon({
	..._shimmerTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
