// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { skaleTitan as _skaleTitan } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for SKALE Titan Hub (chain ID 1350216234). Explorer: https://parallel-stormy-spica.explorer.mainnet.skalenodes.com. Default RPC: https://mainnet.skalenodes.com/v1/parallel-stormy-spica.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const skaleTitan = createCommon({
	..._skaleTitan,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
