// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { skaleCryptoColosseum as _skaleCryptoColosseum } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for SKALE | Crypto Colosseum (chain ID 1032942172). Explorer: https://haunting-devoted-deneb.explorer.mainnet.skalenodes.com. Default RPC: https://mainnet.skalenodes.com/v1/haunting-devoted-deneb.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const skaleCryptoColosseum = createCommon({
	..._skaleCryptoColosseum,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
