// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { nativeDefineChain } from '@tevm/utils'
import { createCommon } from '../createCommon.js'

/**
 * Creates a common configuration for the skaleHumanProtocol chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 1273227453
 * Chain Name: SKALE | Human Protocol
 * Default Block Explorer: https://wan-red-ain.explorer.mainnet.skalenodes.com
 * Default RPC URL: https://mainnet.skalenodes.com/v1/wan-red-ain
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { skaleHumanProtocol } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: skaleHumanProtocol,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const skaleHumanProtocol = createCommon({
	...nativeDefineChain({
		id: 1273227453,
		name: 'SKALE | Human Protocol',
		nativeCurrency: {
			name: 'sFUEL',
			symbol: 'sFUEL',
			decimals: 18,
		},
		rpcUrls: {
			default: {
				http: ['https://mainnet.skalenodes.com/v1/wan-red-ain'],
				webSocket: ['wss://mainnet.skalenodes.com/v1/ws/wan-red-ain'],
			},
		},
		blockExplorers: {
			default: {
				name: 'SKALE Explorer',
				url: 'https://wan-red-ain.explorer.mainnet.skalenodes.com',
			},
		},
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
