// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { skaleRazor as _skaleRazor } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for SKALE | Razor Network (chain ID 278611351). Explorer: https://turbulent-unique-scheat.explorer.mainnet.skalenodes.com. Default RPC: https://mainnet.skalenodes.com/v1/turbulent-unique-scheat.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const skaleRazor = createCommon({
	..._skaleRazor,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
