// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { skaleEuropa as _skaleEuropa } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for SKALE Europa Hub (chain ID 2046399126). Explorer: https://elated-tan-skat.explorer.mainnet.skalenodes.com. Default RPC: https://mainnet.skalenodes.com/v1/elated-tan-skat.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const skaleEuropa = createCommon({
	..._skaleEuropa,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
