// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { skaleHumanProtocol as _skaleHumanProtocol } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for SKALE | Human Protocol (chain ID 1273227453). Explorer: https://wan-red-ain.explorer.mainnet.skalenodes.com. Default RPC: https://mainnet.skalenodes.com/v1/wan-red-ain.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const skaleHumanProtocol = createCommon({
	..._skaleHumanProtocol,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
