// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { skaleCalypso as _skaleCalypso } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for SKALE Calypso Hub (chain ID 1564830818). Explorer: https://honorable-steel-rasalhague.explorer.mainnet.skalenodes.com. Default RPC: https://mainnet.skalenodes.com/v1/honorable-steel-rasalhague.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const skaleCalypso = createCommon({
	..._skaleCalypso,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
