// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { nativeDefineChain } from '@tevm/utils'
import { createCommon } from '../createCommon.js'

/**
 * Creates a common configuration for the skaleTitan chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 1350216234
 * Chain Name: SKALE | Titan Community Hub
 * Default Block Explorer: https://parallel-stormy-spica.explorer.mainnet.skalenodes.com
 * Default RPC URL: https://mainnet.skalenodes.com/v1/parallel-stormy-spica
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { skaleTitan } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: skaleTitan,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const skaleTitan = createCommon({
	...nativeDefineChain({
		id: 1350216234,
		name: 'SKALE | Titan Community Hub',
		nativeCurrency: {
			name: 'sFUEL',
			symbol: 'sFUEL',
			decimals: 18,
		},
		rpcUrls: {
			default: {
				http: ['https://mainnet.skalenodes.com/v1/parallel-stormy-spica'],
				webSocket: ['wss://mainnet.skalenodes.com/v1/ws/parallel-stormy-spica'],
			},
		},
		blockExplorers: {
			default: {
				name: 'SKALE Explorer',
				url: 'https://parallel-stormy-spica.explorer.mainnet.skalenodes.com',
			},
		},
		contracts: {
			multicall3: {
				address: '0xcA11bde05977b3631167028862bE2a173976CA11',
				blockCreated: 2076458,
			},
		},
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
