// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { skaleEuropaTestnet as _skaleEuropaTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for SKALE Europa Testnet (chain ID 1444673419). Explorer: https://juicy-low-small-testnet.explorer.testnet.skalenodes.com. Default RPC: https://testnet.skalenodes.com/v1/juicy-low-small-testnet.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const skaleEuropaTestnet = createCommon({
	..._skaleEuropaTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
