// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { skaleNebulaTestnet as _skaleNebulaTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for SKALE Nebula Testnet (chain ID 37084624). Explorer: https://lanky-ill-funny-testnet.explorer.testnet.skalenodes.com. Default RPC: https://testnet.skalenodes.com/v1/lanky-ill-funny-testnet.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const skaleNebulaTestnet = createCommon({
	..._skaleNebulaTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
