// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { nativeDefineChain } from '@tevm/utils'
import { createCommon } from '../createCommon.js'

/**
 * Creates a common configuration for the skaleNebula chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 1482601649
 * Chain Name: SKALE | Nebula Gaming Hub
 * Default Block Explorer: https://green-giddy-denebola.explorer.mainnet.skalenodes.com
 * Default RPC URL: https://mainnet.skalenodes.com/v1/green-giddy-denebola
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { skaleNebula } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: skaleNebula,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const skaleNebula = createCommon({
	...nativeDefineChain({
		id: 1482601649,
		name: 'SKALE Nebula Hub',
		nativeCurrency: {
			name: 'sFUEL',
			symbol: 'sFUEL',
			decimals: 18,
		},
		rpcUrls: {
			default: {
				http: ['https://mainnet.skalenodes.com/v1/green-giddy-denebola'],
				webSocket: ['wss://mainnet.skalenodes.com/v1/ws/green-giddy-denebola'],
			},
		},
		blockExplorers: {
			default: {
				name: 'SKALE Explorer',
				url: 'https://green-giddy-denebola.explorer.mainnet.skalenodes.com',
			},
		},
		contracts: {
			multicall3: {
				address: '0xcA11bde05977b3631167028862bE2a173976CA11',
				blockCreated: 2372986,
			},
		},
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
