// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { nativeDefineChain } from '@tevm/utils'
import { createCommon } from '../createCommon.js'

/**
 * Creates a common configuration for the skaleTitanTestnet chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 1020352220
 * Chain Name: SKALE Titan Hub
 * Default Block Explorer: https://aware-fake-trim-testnet.explorer.testnet.skalenodes.com
 * Default RPC URL: https://testnet.skalenodes.com/v1/aware-fake-trim-testnet
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { skaleTitanTestnet } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: skaleTitanTestnet,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const skaleTitanTestnet = createCommon({
	...nativeDefineChain({
		id: 1020352220,
		name: 'SKALE Titan Hub',
		nativeCurrency: {
			name: 'sFUEL',
			symbol: 'sFUEL',
			decimals: 18,
		},
		rpcUrls: {
			default: {
				http: ['https://testnet.skalenodes.com/v1/aware-fake-trim-testnet'],
				webSocket: ['wss://testnet.skalenodes.com/v1/ws/aware-fake-trim-testnet'],
			},
		},
		blockExplorers: {
			default: {
				name: 'SKALE Explorer',
				url: 'https://aware-fake-trim-testnet.explorer.testnet.skalenodes.com',
			},
		},
		contracts: {
			multicall3: {
				address: '0xcA11bde05977b3631167028862bE2a173976CA11',
				blockCreated: 104072,
			},
		},
		testnet: true,
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
