// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { nativeDefineChain } from '@tevm/utils'
import { createCommon } from '../createCommon.js'

/**
 * Creates a common configuration for the sketchpad chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 984123
 * Chain Name: Forma Sketchpad
 * Default Block Explorer: https://explorer.sketchpad-1.forma.art
 * Default RPC URL: https://rpc.sketchpad-1.forma.art
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { sketchpad } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: sketchpad,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const sketchpad = createCommon({
	...nativeDefineChain({
		id: 984123,
		name: 'Forma Sketchpad',
		nativeCurrency: {
			symbol: 'TIA',
			name: 'TIA',
			decimals: 18,
		},
		rpcUrls: {
			default: {
				http: ['https://rpc.sketchpad-1.forma.art'],
				webSocket: ['wss://ws.sketchpad-1.forma.art'],
			},
		},
		blockExplorers: {
			default: {
				name: 'Sketchpad Explorer',
				url: 'https://explorer.sketchpad-1.forma.art',
			},
		},
		testnet: true,
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
