// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { sketchpad as _sketchpad } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Forma Sketchpad (chain ID 984123). Explorer: https://explorer.sketchpad-1.forma.art. Default RPC: https://rpc.sketchpad-1.forma.art.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const sketchpad = createCommon({
	..._sketchpad,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
