// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { songbirdTestnet as _songbirdTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Songbird Testnet Coston (chain ID 16). Explorer: https://coston-explorer.flare.network. Default RPC: https://coston-api.flare.network/ext/C/rpc.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const songbirdTestnet = createCommon({
	..._songbirdTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
