// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { songbird as _songbird } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Songbird Canary-Network (chain ID 19). Explorer: https://songbird-explorer.flare.network. Default RPC: https://songbird-api.flare.network/ext/C/rpc.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const songbird = createCommon({
	..._songbird,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
