// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { nativeDefineChain } from '@tevm/utils'
import { createCommon } from '../createCommon.js'

/**
 * Creates a common configuration for the sophonTestnet chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 531050104
 * Chain Name: Sophon Testnet
 * Default Block Explorer: https://explorer.testnet.sophon.xyz
 * Default RPC URL: https://rpc.testnet.sophon.xyz
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { sophonTestnet } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: sophonTestnet,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const sophonTestnet = createCommon({
	...nativeDefineChain({
		id: 531050104,
		name: 'Sophon Testnet',
		nativeCurrency: {
			decimals: 18,
			name: 'Sophon',
			symbol: 'SOPH',
		},
		rpcUrls: {
			default: {
				http: ['https://rpc.testnet.sophon.xyz'],
				webSocket: ['wss://rpc.testnet.sophon.xyz/ws'],
			},
		},
		blockExplorers: {
			default: {
				name: 'Sophon Block Explorer',
				url: 'https://explorer.testnet.sophon.xyz',
			},
		},
		contracts: {
			multicall3: {
				address: '0x83c04d112adedA2C6D9037bb6ecb42E7f0b108Af',
				blockCreated: 15642,
			},
		},
		testnet: true,
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
