// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { spicy as _spicy } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Chiliz Spicy Testnet (chain ID 88882). Explorer: http://spicy-explorer.chiliz.com. Default RPC: https://spicy-rpc.chiliz.com.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const spicy = createCommon({
	..._spicy,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
