// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { storyTestnet as _storyTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Story Testnet (chain ID 1513). Explorer: https://testnet.storyscan.xyz. Default RPC: https://testnet.storyrpc.io.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const storyTestnet = createCommon({
	..._storyTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
