// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { stratis as _stratis } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Stratis Mainnet (chain ID 105105). Explorer: https://explorer.stratisevm.com. Default RPC: https://rpc.stratisevm.com.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const stratis = createCommon({
	..._stratis,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
