// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { taikoHekla as _taikoHekla } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Taiko Hekla L2 (chain ID 167009). Explorer: https://hekla.taikoscan.network. Default RPC: https://rpc.hekla.taiko.xyz.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const taikoHekla = createCommon({
	..._taikoHekla,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
