// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { createCommon } from '../createCommon.js'
import { nativeDefineChain } from '@tevm/utils'

/**
 * Creates a common configuration for the taikoHekla chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 167009
 * Chain Name: Taiko Hekla L2
 * Default Block Explorer: https://hekla.taikoscan.network
 * Default RPC URL: https://rpc.hekla.taiko.xyz
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { taikoHekla } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: taikoHekla,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const taikoHekla = createCommon({
	...nativeDefineChain({
		id: 167009,
		name: 'Taiko Hekla L2',
		nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
		rpcUrls: {
			default: {
				http: ['https://rpc.hekla.taiko.xyz'],
			},
		},
		blockExplorers: {
			default: {
				name: 'Taikoscan',
				url: 'https://hekla.taikoscan.network',
			},
		},
		contracts: {
			multicall3: {
				address: '0xca11bde05977b3631167028862be2a173976ca11',
				blockCreated: 59757,
			},
		},
		testnet: true,
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
