// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { taikoTestnetSepolia as _taikoTestnetSepolia } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Taiko (Alpha-3 Testnet) (chain ID 167005). Explorer: https://explorer.test.taiko.xyz. Default RPC: https://rpc.test.taiko.xyz.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const taikoTestnetSepolia = createCommon({
	..._taikoTestnetSepolia,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
