// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { taraxa as _taraxa } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Taraxa Mainnet (chain ID 841). Explorer: https://explorer.mainnet.taraxa.io. Default RPC: https://rpc.mainnet.taraxa.io.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const taraxa = createCommon({
	..._taraxa,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
