// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { createCommon } from '../createCommon.js'
import { nativeDefineChain } from '@tevm/utils'

/**
 * Creates a common configuration for the taraxa chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 841
 * Chain Name: Taraxa Mainnet
 * Default Block Explorer: https://explorer.mainnet.taraxa.io
 * Default RPC URL: https://rpc.mainnet.taraxa.io
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { taraxa } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: taraxa,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const taraxa = createCommon({
	...nativeDefineChain({
		id: 841,
		name: 'Taraxa Mainnet',
		nativeCurrency: { name: 'Tara', symbol: 'TARA', decimals: 18 },
		rpcUrls: {
			default: {
				http: ['https://rpc.mainnet.taraxa.io'],
			},
		},
		blockExplorers: {
			default: {
				name: 'Taraxa Explorer',
				url: 'https://explorer.mainnet.taraxa.io',
			},
		},
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
