// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { telcoinTestnet as _telcoinTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Telcoin Adiri Testnet (chain ID 2017). Explorer: https://telscan.io. Default RPC: https://rpc.telcoin.network.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const telcoinTestnet = createCommon({
	..._telcoinTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
