// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { telosTestnet as _telosTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Telos (chain ID 41). Explorer: https://testnet.teloscan.io/. Default RPC: https://rpc.testnet.telos.net.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const telosTestnet = createCommon({
	..._telosTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
