// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { telos as _telos } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Telos (chain ID 40). Explorer: https://www.teloscan.io/. Default RPC: https://rpc.telos.net.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const telos = createCommon({
	..._telos,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
