// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { createCommon } from '../createCommon.js'
import { nativeDefineChain } from '@tevm/utils'

/**
 * Creates a common configuration for the tenet chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 1559
 * Chain Name: Tenet
 * Default Block Explorer: https://tenetscan.io
 * Default RPC URL: https://rpc.tenet.org
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { tenet } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: tenet,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const tenet = createCommon({
	...nativeDefineChain({
		id: 1559,
		name: 'Tenet',
		nativeCurrency: {
			name: 'TENET',
			symbol: 'TENET',
			decimals: 18,
		},
		rpcUrls: {
			default: {
				http: ['https://rpc.tenet.org'],
			},
		},
		blockExplorers: {
			default: {
				name: 'TenetScan Mainnet',
				url: 'https://tenetscan.io',
				apiUrl: 'https://tenetscan.io/api',
			},
		},
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
