// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { tenet as _tenet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Tenet (chain ID 1559). Explorer: https://tenetscan.io. Default RPC: https://rpc.tenet.org.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const tenet = createCommon({
	..._tenet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
