// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { thaiChain as _thaiChain } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for ThaiChain (chain ID 7). Explorer: https://exp.thaichain.org. Default RPC: https://rpc.thaichain.org.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const thaiChain = createCommon({
	..._thaiChain,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
