// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { nativeDefineChain } from '@tevm/utils'
import { createCommon } from '../createCommon.js'

/**
 * Creates a common configuration for the thaiChain chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 7
 * Chain Name: ThaiChain
 * Default Block Explorer: https://exp.thaichain.org
 * Default RPC URL: https://rpc.thaichain.org
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { thaiChain } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: thaiChain,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const thaiChain = createCommon({
	...nativeDefineChain({
		id: 7,
		name: 'ThaiChain',
		nativeCurrency: {
			name: 'TCH',
			symbol: 'TCH',
			decimals: 18,
		},
		rpcUrls: {
			default: {
				http: ['https://rpc.thaichain.org'],
			},
		},
		blockExplorers: {
			default: {
				name: 'Blockscout',
				url: 'https://exp.thaichain.org',
				apiUrl: 'https://exp.thaichain.org/api',
			},
		},
		contracts: {
			multicall3: {
				address: '0x0DaD6130e832c21719C5CE3bae93454E16A84826',
				blockCreated: 4806386,
			},
		},
		testnet: false,
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
