// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { nativeDefineChain } from '@tevm/utils'
import { createCommon } from '../createCommon.js'

/**
 * Creates a common configuration for the thunderTestnet chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 997
 * Chain Name: 5ireChain Thunder Testnet
 * Default Block Explorer: https://testnet.5irescan.io/
 * Default RPC URL: https://rpc.testnet.5ire.network
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { thunderTestnet } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: thunderTestnet,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const thunderTestnet = createCommon({
	...nativeDefineChain({
		id: 997,
		name: '5ireChain Thunder Testnet',
		nativeCurrency: {
			name: '5ire Token',
			symbol: '5IRE',
			decimals: 18,
		},
		rpcUrls: {
			default: {
				http: ['https://rpc.testnet.5ire.network'],
			},
		},
		blockExplorers: {
			default: {
				name: '5ireChain Thunder Explorer',
				url: 'https://testnet.5irescan.io/',
			},
		},
		testnet: true,
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
