// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { thunderTestnet as _thunderTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for 5ireChain Thunder Testnet (chain ID 997). Explorer: https://testnet.5irescan.io/. Default RPC: https://rpc.testnet.5ire.network.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const thunderTestnet = createCommon({
	..._thunderTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
