// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { tron as _tron } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Tron (chain ID 728126428). Explorer: https://tronscan.org. Default RPC: https://api.trongrid.io/jsonrpc.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const tron = createCommon({
	..._tron,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
