// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { vechain as _vechain } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Vechain (chain ID 100009). Explorer: https://explore.vechain.org. Default RPC: https://mainnet.vechain.org.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const vechain = createCommon({
	..._vechain,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
