// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { wanchainTestnet as _wanchainTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Wanchain Testnet (chain ID 999). Explorer: https://wanscan.org. Default RPC: https://gwan-ssl.wandevs.org:46891.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const wanchainTestnet = createCommon({
	..._wanchainTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
