// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { wemix as _wemix } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for WEMIX (chain ID 1111). Explorer: https://explorer.wemix.com. Default RPC: https://api.wemix.com.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const wemix = createCommon({
	..._wemix,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
