// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { x1Testnet as _x1Testnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for X1 Testnet (chain ID 1952). Explorer: https://www.oklink.com/xlayer-test. Default RPC: https://xlayertestrpc.okx.com.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const x1Testnet = createCommon({
	..._x1Testnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
