// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { createCommon } from '../createCommon.js'
import { nativeDefineChain } from '@tevm/utils'

/**
 * Creates a common configuration for the x1Testnet chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 195
 * Chain Name: X1 Testnet
 * Default Block Explorer: https://www.oklink.com/xlayer-test
 * Default RPC URL: https://xlayertestrpc.okx.com
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { x1Testnet } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: x1Testnet,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const x1Testnet = createCommon({
	...nativeDefineChain({
		id: 195,
		name: 'X1 Testnet',
		nativeCurrency: {
			decimals: 18,
			name: 'OKB',
			symbol: 'OKB',
		},
		rpcUrls: {
			default: {
				http: ['https://xlayertestrpc.okx.com'],
			},
		},
		blockExplorers: {
			default: {
				name: 'OKLink',
				url: 'https://www.oklink.com/xlayer-test',
			},
		},
		contracts: {
			multicall3: {
				address: '0xca11bde05977b3631167028862be2a173976ca11',
				blockCreated: 624344,
			},
		},
		testnet: true,
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
