// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { createCommon } from '../createCommon.js'
import { nativeDefineChain } from '@tevm/utils'

/**
 * Creates a common configuration for the xai chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 660279
 * Chain Name: Xai Mainnet
 * Default Block Explorer: https://explorer.xai-chain.net
 * Default RPC URL: https://xai-chain.net/rpc
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { xai } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: xai,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const xai = createCommon({
	...nativeDefineChain({
		id: 660279,
		name: 'Xai Mainnet',
		nativeCurrency: {
			name: 'Xai',
			symbol: 'XAI',
			decimals: 18,
		},
		rpcUrls: {
			default: {
				http: ['https://xai-chain.net/rpc'],
			},
		},
		blockExplorers: {
			default: {
				name: 'Blockscout',
				url: 'https://explorer.xai-chain.net',
			},
		},
		contracts: {
			multicall3: {
				address: '0xca11bde05977b3631167028862be2a173976ca11',
				blockCreated: 222549,
			},
		},
		testnet: false,
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
