// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { xai as _xai } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Xai Mainnet (chain ID 660279). Explorer: https://explorer.xai-chain.net. Default RPC: https://xai-chain.net/rpc.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const xai = createCommon({
	..._xai,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
