// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { xaiTestnet as _xaiTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Xai Testnet (chain ID 37714555429). Explorer: https://testnet-explorer-v2.xai-chain.net. Default RPC: https://testnet-v2.xai-chain.net/rpc.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const xaiTestnet = createCommon({
	..._xaiTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
