// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { createCommon } from '../createCommon.js'
import { nativeDefineChain } from '@tevm/utils'

/**
 * Creates a common configuration for the xdc chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 50
 * Chain Name: XDC Network
 * Default Block Explorer: https://xdcscan.com
 * Default RPC URL: https://rpc.xdcrpc.com
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { xdc } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: xdc,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const xdc = createCommon({
	...nativeDefineChain({
		id: 50,
		name: 'XDC Network',
		nativeCurrency: {
			decimals: 18,
			name: 'XDC',
			symbol: 'XDC',
		},
		rpcUrls: {
			default: {
				http: ['https://rpc.xdcrpc.com'],
			},
		},
		blockExplorers: {
			default: {
				name: 'XDCScan',
				url: 'https://xdcscan.com',
			},
		},
		contracts: {
			multicall3: {
				address: '0x0B1795ccA8E4eC4df02346a082df54D437F8D9aF',
				blockCreated: 75884020,
			},
		},
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
