// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { xdc as _xdc } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for XDC Network (chain ID 50). Explorer: https://xdcscan.com. Default RPC: https://rpc.xdcrpc.com.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const xdc = createCommon({
	..._xdc,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
