// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { createCommon } from '../createCommon.js'
import { nativeDefineChain } from '@tevm/utils'

/**
 * Creates a common configuration for the xdcTestnet chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 51
 * Chain Name: Apothem Network
 * Default Block Explorer: https://testnet.xdcscan.com
 * Default RPC URL: https://erpc.apothem.network
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { xdcTestnet } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: xdcTestnet,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const xdcTestnet = createCommon({
	...nativeDefineChain({
		id: 51,
		name: 'Apothem Network',
		nativeCurrency: {
			decimals: 18,
			name: 'TXDC',
			symbol: 'TXDC',
		},
		rpcUrls: {
			default: {
				http: ['https://erpc.apothem.network'],
			},
		},
		blockExplorers: {
			default: {
				name: 'XDCScan',
				url: 'https://testnet.xdcscan.com',
			},
		},
		contracts: {
			multicall3: {
				address: '0xca11bde05977b3631167028862be2a173976ca11',
				blockCreated: 59765389,
			},
		},
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
