// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { xdcTestnet as _xdcTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Apothem Network (chain ID 51). Explorer: https://testnet.xdcscan.com. Default RPC: https://erpc.apothem.network.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const xdcTestnet = createCommon({
	..._xdcTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
