// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { createCommon } from '../createCommon.js'
import { nativeDefineChain } from '@tevm/utils'

/**
 * Creates a common configuration for the xLayer chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 196
 * Chain Name: X Layer Mainnet
 * Default Block Explorer: https://www.oklink.com/xlayer
 * Default RPC URL: https://rpc.xlayer.tech
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { xLayer } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: xLayer,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const xLayer = createCommon({
	...nativeDefineChain({
		id: 196,
		name: 'X Layer Mainnet',
		nativeCurrency: {
			decimals: 18,
			name: 'OKB',
			symbol: 'OKB',
		},
		rpcUrls: {
			default: {
				http: ['https://rpc.xlayer.tech'],
			},
		},
		blockExplorers: {
			default: {
				name: 'OKLink',
				url: 'https://www.oklink.com/xlayer',
				apiUrl: 'https://www.oklink.com/api/v5/explorer/xlayer/api',
			},
		},
		contracts: {
			multicall3: {
				address: '0xcA11bde05977b3631167028862bE2a173976CA11',
				blockCreated: 47416,
			},
		},
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
