// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { xrSepolia as _xrSepolia } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for XR Sepolia (chain ID 2730). Explorer: https://xr-sepolia-testnet.explorer.caldera.xyz. Default RPC: https://xr-sepolia-testnet.rpc.caldera.xyz/http.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const xrSepolia = createCommon({
	..._xrSepolia,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
