// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { yooldoVerseTestnet as _yooldoVerseTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Yooldo Verse Testnet (chain ID 50006). Explorer: https://explorer.testnet.yooldo-verse.xyz. Default RPC: https://rpc.testnet.yooldo-verse.xyz.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const yooldoVerseTestnet = createCommon({
	..._yooldoVerseTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
