// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { createCommon } from '../createCommon.js'
import { nativeDefineChain } from '@tevm/utils'

/**
 * Creates a common configuration for the zetachainAthensTestnet chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 7001
 * Chain Name: ZetaChain Athens Testnet
 * Default Block Explorer: https://testnet.zetascan.com
 * Default RPC URL: https://zetachain-athens-evm.blockpi.network/v1/rpc/public
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { zetachainAthensTestnet } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: zetachainAthensTestnet,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const zetachainAthensTestnet = createCommon({
	...nativeDefineChain({
		id: 7001,
		name: 'ZetaChain Athens Testnet',
		nativeCurrency: {
			decimals: 18,
			name: 'Zeta',
			symbol: 'aZETA',
		},
		rpcUrls: {
			default: {
				http: ['https://zetachain-athens-evm.blockpi.network/v1/rpc/public'],
			},
		},
		blockExplorers: {
			default: {
				name: 'ZetaScan',
				url: 'https://testnet.zetascan.com',
			},
		},
		contracts: {
			multicall3: {
				address: '0xcA11bde05977b3631167028862bE2a173976CA11',
				blockCreated: 2715217,
			},
		},
		testnet: true,
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
