// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { zhejiang as _zhejiang } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Zhejiang (chain ID 1337803). Explorer: https://zhejiang.beaconcha.in. Default RPC: https://rpc.zhejiang.ethpandaops.io.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const zhejiang = createCommon({
	..._zhejiang,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
