// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { zilliqa as _zilliqa } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Zilliqa (chain ID 32769). Explorer: https://evmx.zilliqa.com. Default RPC: https://api.zilliqa.com.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const zilliqa = createCommon({
	..._zilliqa,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
