// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { zkFairTestnet as _zkFairTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for ZKFair Testnet (chain ID 43851). Explorer: https://testnet-scan.zkfair.io. Default RPC: https://testnet-rpc.zkfair.io.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const zkFairTestnet = createCommon({
	..._zkFairTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
