// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { createCommon } from '../createCommon.js'
import { nativeDefineChain } from '@tevm/utils'

/**
 * Creates a common configuration for the zkFairTestnet chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 43851
 * Chain Name: ZKFair Testnet
 * Default Block Explorer: https://testnet-scan.zkfair.io
 * Default RPC URL: https://testnet-rpc.zkfair.io
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { zkFairTestnet } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: zkFairTestnet,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const zkFairTestnet = createCommon({
	...nativeDefineChain({
		id: 43851,
		name: 'ZKFair Testnet',
		nativeCurrency: {
			decimals: 18,
			name: 'USD Coin',
			symbol: 'USDC',
		},
		rpcUrls: {
			default: {
				http: ['https://testnet-rpc.zkfair.io'],
			},
		},
		blockExplorers: {
			default: {
				name: 'zkFair Explorer',
				url: 'https://testnet-scan.zkfair.io',
			},
		},
		testnet: true,
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
