// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { zkFair as _zkFair } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for ZKFair Mainnet (chain ID 42766). Explorer: https://scan.zkfair.io. Default RPC: https://rpc.zkfair.io.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const zkFair = createCommon({
	..._zkFair,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
