// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { createCommon } from '../createCommon.js'
import { nativeDefineChain } from '@tevm/utils'

/**
 * Creates a common configuration for the zkLinkNovaSepoliaTestnet chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 810181
 * Chain Name: zkLink Nova Sepolia Testnet
 * Default Block Explorer: https://sepolia.explorer.zklink.io
 * Default RPC URL: https://sepolia.rpc.zklink.io
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { zkLinkNovaSepoliaTestnet } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: zkLinkNovaSepoliaTestnet,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const zkLinkNovaSepoliaTestnet = createCommon({
	...nativeDefineChain({
		id: 810181,
		name: 'zkLink Nova Sepolia Testnet',
		nativeCurrency: {
			decimals: 18,
			name: 'ETH',
			symbol: 'ETH',
		},
		rpcUrls: {
			default: {
				http: ['https://sepolia.rpc.zklink.io'],
			},
		},
		blockExplorers: {
			default: {
				name: 'zkLink Nova Block Explorer',
				url: 'https://sepolia.explorer.zklink.io',
			},
		},
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
