// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { zkLinkNova as _zkLinkNova } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for zkLink Nova (chain ID 810180). Explorer: https://explorer.zklink.io. Default RPC: https://rpc.zklink.io.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const zkLinkNova = createCommon({
	..._zkLinkNova,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
