// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { zkLinkNovaSepoliaTestnet as _zkLinkNovaSepoliaTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for zkLink Nova Sepolia Testnet (chain ID 810181). Explorer: https://sepolia.explorer.zklink.io. Default RPC: https://sepolia.rpc.zklink.io.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const zkLinkNovaSepoliaTestnet = createCommon({
	..._zkLinkNovaSepoliaTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
