// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { zksyncLocalNode as _zksyncLocalNode } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for ZKsync CLI Local Node (chain ID 270). Explorer: —. Default RPC: http://localhost:3050.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const zksyncLocalNode = createCommon({
	..._zksyncLocalNode,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
