// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { zksync as _zksync } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for ZKsync Era (chain ID 324). Explorer: https://explorer.zksync.io/. Default RPC: https://mainnet.era.zksync.io.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const zksync = createCommon({
	..._zksync,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
