// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { createCommon } from '../createCommon.js'
import { nativeDefineChain } from '@tevm/utils'

/**
 * Creates a common configuration for the zksyncInMemoryNode chain.
 * @type {import('../Common.js').Common}
 * @description
 * Chain ID: 260
 * Chain Name: ZKsync InMemory Node
 * Default Block Explorer: Not specified
 * Default RPC URL: http://localhost:8011
 * @example
 * import { createMemoryClient } from 'tevm'
 * import { zksyncInMemoryNode } from 'tevm/common'
 * import { http } from 'tevm'
 *
 * const client = createMemoryClient({
 *   common: zksyncInMemoryNode,
 *   fork: {
 *     transport: http({ url: 'https://example.com' })({})
 *   },
 * })
 */
export const zksyncInMemoryNode = createCommon({
	...nativeDefineChain({
		id: 260,
		name: 'ZKsync InMemory Node',
		nativeCurrency: {
			name: 'Ether',
			symbol: 'ETH',
			decimals: 18,
		},
		rpcUrls: {
			default: {
				http: ['http://localhost:8011'],
			},
		},
		testnet: true,
	}),
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
