// This file was auto-generated by __GENERATE_CHAIN_PRESETS__.js. Do not edit manually.

import { zoraTestnet as _zoraTestnet } from 'viem/chains'
import { createCommon } from '../createCommon.js'

/**
 * `Common` for Zora Goerli Testnet (chain ID 999). Explorer: https://testnet.explorer.zora.energy. Default RPC: https://testnet.rpc.zora.energy.
 *
 * Usage: pass as `common` to `createMemoryClient`. See `tevmDefault` and other presets in `tevm/common`.
 * @hidden
 * @type {import('../Common.js').Common}
 */
export const zoraTestnet = createCommon({
	..._zoraTestnet,
	loggingLevel: 'warn',
	eips: [],
	hardfork: 'prague',
})
