# Load plugin including Tevm plugin
# Tevm is configured in the tsconfig.json
# in future it will be configured via tevm.config.ts
preload = ["./plugins.js"]

# Use plugin in tests too
[test]
preload = ["./plugins.js"]

