/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Generate the JavaScript runtime code for a Solidity contract */
export declare function generateRuntimeJs(solcOutputJson: string, moduleType: string, useScopedPackage: boolean): string
