on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
  merge_group:

name: Build types

jobs:
  build:
    name: Build types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: "Setup"
        uses: ./.github/actions/setup

      - name: Run build:types
        run: pnpm nx affected --target=build:types
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

