name: CI Checks
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  TEVM_TEST_ALCHEMY_KEY: ${{ secrets.TEVM_TEST_ALCHEMY_KEY }}
  TEVM_RPC_URLS_MAINNET: ${{ secrets.TEVM_RPC_URLS_MAINNET }}
  TEVM_RPC_URLS_OPTIMISM: ${{ secrets.TEVM_RPC_URLS_OPTIMISM }}

jobs:
  cichecks:
    name: CI Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout [Pull Request]
        if: ${{ github.event_name == 'pull_request' }}
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - uses: actions/checkout@v4
        name: Checkout [Default Branch]
        if: ${{ github.event_name != 'pull_request' }}
        with:
          fetch-depth: 0

      - name: "Setup"
        uses: ./.github/actions/setup

      - name: Build dist
        run: pnpm -r build:dist

      - name: Build types
        run: pnpm -r build:types

      - name: Tests
        run: pnpm -r test:coverage

      - name: Fixtures
        run: pnpm -r dev:run

      - name: Tests Rust
        run: pnpm -r test:rust

      - name: Typecheck
        run: pnpm -r typecheck

      - name: Lint
        run: pnpm -r lint:check

      - name: Lint deps
        run: pnpm -r lint:deps

      - name: Lint packages
        run: pnpm -r lint:package

      - name: Build app
        run: pnpm -r build:app

      - name: Generate docs
        run: pnpm -r generate:docs

      - name: Build rust
        run: pnpm -r build:rust

      - name: Build wasm
        run: pnpm -r build:asm
