name: CI Checks
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  TEVM_TEST_ALCHEMY_KEY: ${{ secrets.TEVM_TEST_ALCHEMY_KEY }}
  TEVM_RPC_URLS_MAINNET: ${{ secrets.TEVM_RPC_URLS_MAINNET }}
  TEVM_RPC_URLS_OPTIMISM: ${{ secrets.TEVM_RPC_URLS_OPTIMISM }}

jobs:
  ci-checks:
    name: CI Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout [Pull Request]
        if: ${{ github.event_name == 'pull_request' }}
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - uses: actions/checkout@v4
        name: Checkout [Default Branch]
        if: ${{ github.event_name != 'pull_request' }}
        with:
          fetch-depth: 0

      - name: "Setup"
        id: setup
        uses: ./.github/actions/setup

      - name: Build dist
        id: build-dist
        run: pnpm -r build:dist

      - name: Build types
        if: success()
        continue-on-error: true
        run: pnpm -r build:types

      - name: Tests
        if: always() && steps.setup.conclusion == 'success' && steps.build-dist.conclusion == 'success'
        continue-on-error: true
        run: pnpm -r test:coverage

      - name: Fixtures
        if: always() && steps.setup.conclusion == 'success' && steps.build-dist.conclusion == 'success'
        continue-on-error: true
        run: pnpm -r dev:run

      - name: Tests Rust
        if: always() && steps.setup.conclusion == 'success' && steps.build-dist.conclusion == 'success'
        continue-on-error: true
        run: pnpm -r test:rust

      - name: Typecheck
        if: always() && steps.setup.conclusion == 'success' && steps.build-dist.conclusion == 'success'
        continue-on-error: true
        run: pnpm -r typecheck

      - name: Lint
        if: always() && steps.setup.conclusion == 'success' && steps.build-dist.conclusion == 'success'
        continue-on-error: true
        run: pnpm -r lint:check

      - name: Lint deps
        if: always() && steps.setup.conclusion == 'success' && steps.build-dist.conclusion == 'success'
        continue-on-error: true
        run: pnpm -r lint:deps

      - name: Lint packages
        if: always() && steps.setup.conclusion == 'success' && steps.build-dist.conclusion == 'success'
        continue-on-error: true
        run: pnpm -r lint:package

      - name: Build app
        if: always() && steps.setup.conclusion == 'success' && steps.build-dist.conclusion == 'success'
        continue-on-error: true
        run: pnpm -r build:app

      - name: Generate docs
        if: always() && steps.setup.conclusion == 'success' && steps.build-dist.conclusion == 'success'
        continue-on-error: true
        run: pnpm -r generate:docs

      - name: Build rust
        if: always() && steps.setup.conclusion == 'success' && steps.build-dist.conclusion == 'success'
        continue-on-error: true
        run: pnpm -r build:rust

      - name: Build wasm
        if: always() && steps.setup.conclusion == 'success' && steps.build-dist.conclusion == 'success'
        continue-on-error: true
        run: pnpm -r build:wasm

      - name: Check Results
        if: always()
        run: |
          echo "| Task | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|------|--------|" >> $GITHUB_STEP_SUMMARY

          failed=""
          steps_json='${{ toJson(steps) }}'

          for step in build-types tests fixtures tests-rust typecheck lint lint-deps lint-packages build-app generate-docs build-rust build-wasm; do
            conclusion=$(echo "$steps_json" | jq -r ".\"$step\".conclusion // \"skipped\"")
            name=$(echo "$step" | sed 's/-/ /g' | sed 's/\b\w/\U&/g')  # Convert to Title Case

            if [[ "$conclusion" == "success" ]]; then
              echo "| $name | ✅ |" >> $GITHUB_STEP_SUMMARY
            else
              echo "| $name | ❌ |" >> $GITHUB_STEP_SUMMARY
              failed="$failed $step"
            fi
          done

          [[ -n "$failed" ]] && { echo "❌ Failed:$failed" >> $GITHUB_STEP_SUMMARY; exit 1; } || echo "✅ All tasks passed" >> $GITHUB_STEP_SUMMARY
