name: CI Checks
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: true
  # give extra memory to speed up a bit
  NODE_OPTIONS: "--max_old_space_size=4096"
  NX_BRANCH: ${{ github.event.number || github.ref_name }}
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
  TEVM_TEST_ALCHEMY_KEY: ${{ secrets.TEVM_TEST_ALCHEMY_KEY }}
  TEVM_RPC_URLS_MAINNET: ${{ secrets.TEVM_RPC_URLS_MAINNET }}
  TEVM_RPC_URLS_OPTIMISM: ${{ secrets.TEVM_RPC_URLS_OPTIMISM }}

jobs:
  cichecks:
    name: CI Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout [Pull Request]
        if: ${{ github.event_name == 'pull_request' }}
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - uses: actions/checkout@v4
        name: Checkout [Default Branch]
        if: ${{ github.event_name != 'pull_request' }}
        with:
          fetch-depth: 0

      - name: "Setup"
        uses: ./.github/actions/setup

      - run: npx nx-cloud start-ci-run --distribute-on="6 linux-medium-js" --stop-agents-after="build:app"

      - name: Build
        run: pnpm nx affected --targets=build:dist,build:types

      - name: Tests
        run: pnpm nx affected --targets=test:coverage,dev:run

      - name: Lint
        run: pnpm nx affected --targets=typecheck,lint:check,lint:deps,lint:package

      - name: Build app
        run: pnpm nx affected --targets=build:app,generate:docs