on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
  merge_group:

name: E2E

jobs:
  check:
    name: E2E
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: "Setup"
        uses: ./.github/actions/setup

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run tests
        run: echo "WIP" # pnpm nx e2e e2e
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
