on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

name: Test fixtures

jobs:
  fixtures:
    name: Test fixtures
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: "Setup"
        uses: ./.github/actions/setup

      - name: Run dev fixtures
        run: bun nx run-many --target=dev:run
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
          RPC_URL_MAINNET: ${{ secrets.RPC_URL_MAINNET }}

