on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
  merge_group:

name: Sort Package Json

jobs:
  check:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: "Setup"
        uses: ./.github/actions/setup

      - name: Run Package.json formatter - Run `pnpm sort-package-json` to fix
        run: pnpm sort-package-json:check
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
