name: Zig CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  zig:
    name: Nx Cloud - Main Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout [Pull Request]
        if: ${{ github.event_name == 'pull_request' }}
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - uses: actions/checkout@v4
        name: Checkout [Default Branch]
        if: ${{ github.event_name != 'pull_request' }}
        with:
          fetch-depth: 0

      - name: "Setup"
        uses: ./.github/actions/setup

      - name: Initialize the Nx Cloud distributed CI run and stop agents when the build tasks are done
        run: bunx nx-cloud start-ci-run --stop-agents-after=build:app --stop-agents-on-failure=false

      - name: Build Rust Zig and WASM
        run: |
          cargo build &&
          zig build &&
          zig build wasm && echo "WASM size: $(ls -lh ./dist/zigevm.wasm | awk '{print $5}')"

      - name: Run Zig tests
        run: |
          zig build test-all && echo "✅ Tests passed"
